Bridge/Bridge.csproj
Bridge/Resources/build.bat

Added folder-independent Pre-built Event

Added folder-independent Pre-built Event

---

Bridge/Resources/String.js
Bridge/System/String.cs

https://github.com/bridgedotnet/Bridge/issues/393

[FIX] String Comparison issue with enum emit #393

---

.gitignore
Bridge/Attributes/IgnoreAttribute.cs
Bridge/Bridge.csproj
Bridge/Resources/Array.js
Bridge/Resources/Collections/ArrayEnumerator.js
Bridge/Resources/Collections/CustomEnumerator.js
Bridge/Resources/list
Bridge/System/Array.cs
Bridge/System/Collections/Generic/IEnumerator.cs
Compiler/Contract/IAssemblyInfo.cs
Compiler/Contract/ITranslator.cs
Compiler/Translator/Emitter/Emitter.Visitor.cs
Compiler/Translator/Inspector/Visitor.Exception.cs
Compiler/Translator/Translator/Translator.Properties.cs
Compiler/Translator/Translator/Translator.cs
Compiler/Translator/Utils/AssemblyInfo.cs

[ADD] Inject generated script as embedded resource #413
[ADD] Array methods

Inject generated script as embedded resource

---

Compiler/Translator/Emitter/Blocks/AssignmentBlock.cs

https://github.com/bridgedotnet/Bridge/issues/439

[FIX] [#439] Invalid JS built from custom 1.8 build

---

Compiler/Contract/Helpers.cs
Compiler/Translator/Emitter/Blocks/CastBlock.cs
Compiler/Translator/Emitter/Blocks/InvocationBlock.cs
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/test.bridgeIssues.n384.js
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/testIssue475A.js
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/testIssue475B.js
Compiler/TranslatorTests/TestProjects/16/BridgeIssues/TestIssue475A.cs
Compiler/TranslatorTests/TestProjects/16/BridgeIssues/TestIssue475B.cs
Compiler/TranslatorTests/TestProjects/16/test.csproj

https://github.com/bridgedotnet/Bridge/issues/475

[FIX] [#475] Extension method invocation generates invalid code

---

Compiler/TranslatorTests/TestProjects/16/Bridge/reference/test.bridgeIssues.n384.js
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/test.bridgeIssues.n411.js
Compiler/TranslatorTests/TestProjects/16/BridgeIssues/N411.cs
Compiler/TranslatorTests/TestProjects/16/test.csproj
Html5/Interfaces/CanvasRenderingContext2D.cs

[FIX] [#411] CanvasRenderingContext2D.FillText() maxWidth parameter default value doesn't work

---

CODE_OF_CONDUCT.md

Join the Contributor Covenant community

---

Compiler/Translator/Emitter/Blocks/InvocationBlock.cs
Testing/tests/client/Tests/BridgeIssues/N558.cs
Testing/tests/client/Tests/RunTests.cs
Testing/tests/client/client.csproj

https://github.com/bridgedotnet/Bridge/issues/558

[FIX][#558] Issue with polymorphism in inherited class

---

Compiler/Translator/Translator/Translator.ProjectReader.cs

[FIX] [#645] Bridge 1.10.0 subsequent builds might fail

---

Compiler/Builder/Program.cs
Compiler/Translator/Emitter/Blocks/ConstructorBlock.Events.cs
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/testIssue599.js
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/testIssue599.min.js
Compiler/TranslatorTests/TestProjects/18/TestIssue599ReadyAttribute.cs
Html5/Events/EventAttributes.cs

https://github.com/bridgedotnet/Bridge/issues/686

Issue686 If Ready attribute is applied to instance method then compiler should raise an exception

---

Html5/Document.cs
Html5/DocumentInstance.cs
Html5/Global.cs
Html5/Node/Element.cs
Html5/Window.cs
Html5/WindowInstance.cs

https://github.com/bridgedotnet/Bridge/issues/729

[FIX] [#729] Document.OnKeyDown must be Action<KeyboardEvent>

---

Html5/Events/AnimationEvent.cs
Html5/Events/CompositionEvent.cs
Html5/Events/CustomEvent.cs
Html5/Events/Event.cs
Html5/Events/FocusEvent.cs
Html5/Events/HashChangeEvent.cs
Html5/Events/KeyboardEvent.cs
Html5/Events/MouseEvent.cs
Html5/Events/ProgressEvent.cs
Html5/Events/UIEvent.cs
Html5/Events/WheelEvent.cs
Html5/Node/Element.cs

[#729] Generic versions of Event classes + changing Element<>'s Events to MouseEvent and KeyboardEvent where applicable

---

Compiler/Translator/Translator/Plugins.cs
Compiler/Translator/Translator/Translator.cs

https://github.com/bridgedotnet/Bridge/issues/799

[ADD] [#799] Ability to store plugins like embedded resources inside bridge libraries

---

Compiler/Contract/Helpers.cs
Compiler/Translator/Inspector/Inspector.Visitor.cs

Prevent autoPropertyToField for interface properties (fixes #770)

---

Html5/Bridge.Html5.csproj

[#838] DllImport warning with extern modifier

---

Compiler/Translator/Translator/Plugins.cs
Compiler/Translator/Translator/Translator.cs

Testing. Minifier.

---

Compiler/Contract/OverloadsCollection.cs

https://github.com/bridgedotnet/Bridge/issues/847

[FIX] [#847] Bridge emits wrong member name sometime

---

Compiler/Translator/Emitter/Blocks/BreakBlock.cs
Compiler/Translator/Utils/LambdaVisitor.cs
Testing/tests/client/BridgeIssues/N841.cs
Testing/tests/client/Tests/BridgeIssues/N841.cs
Testing/tests/client/client.csproj
Testing/www/js/code.js
Testing/www/js/test.js

https://github.com/bridgedotnet/Bridge/issues/841

Issue841 Switch statement within foreach loop may produce invalid javascript

---

.nuget/Bridge.Compiler.nuspec
.nuget/Bridge.Contract.nuspec
.nuget/Bridge.Html5.Dev.nuspec
Bridge.sln
Bridge/build/package/nuget-package-source/collect-nuget-packages.bat
Html5/Bridge.Html5.csproj

Bridge.Html5.Dev package depending on Bridge.Dev package

Testing.Html5 package

---

.nuget/NuGet.Build.Package.targets
Bridge/Bridge.csproj
Compiler/Build/Bridge.Build.csproj
Compiler/Contract/Bridge.Contract.csproj
Compiler/Translator/Bridge.Translator.csproj
Html5/Bridge.Html5.csproj
Testing/tests/client/App_Readme/Bridge.NET/README.Collections.txt
Testing/tests/client/client.csproj
Testing/tests/client/packages.config
Testing/www/js/bridge.collections.js

* Nuget packaging enhancements:
- <NuGetUseExplicitVersion>true</NuGetUseExplicitVersion> in this case version goes from nuspec, otherwise from assembly version (by default)
- all nuget packaging staff grouped in one block and placed in the end of csproj-es
* Using Bridge.Collections.Dev package for client test project

Tetsing.NuGet packaging

---

Compiler/Contract/ITypeInfo.cs
Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/Inspector/Inspector.Visitor.cs
Compiler/Translator/Utils/TypeInfo.cs
Testing/tests/client/BridgeIssues/N857.cs
Testing/tests/client/client.csproj
Testing/www/js/bridge.collections.js
Testing/www/js/code.js
Testing/www/js/test.js

https://github.com/bridgedotnet/Bridge/issues/857

Issue857 Compiler crash due to unsigned enum

---

Compiler/Build/GenerateScript.cs
Compiler/Builder/Program.cs
Compiler/Contract/IAssemblyInfo.cs
Compiler/Translator/Translator/Translator.cs
Compiler/Translator/Utils/AssemblyInfo.cs

[#876] CleanOutputFolderBeforeBuild config option enhancements

---

Testing/tests/client/BridgeIssues/N508.cs
Testing/tests/client/BridgeIssues/N690.cs
Testing/tests/client/client.csproj
Testing/tests/clientOne/clientOne.csproj
Testing/www/js/code.js
Testing/www/js/test.js
Testing/www/jsOne/test.js

Use newly added Bridge.Test async support for testing issues #508 and #590

Testing.Async support

---

Compiler/Translator/Emitter/Blocks/ConditionalBlock.cs
Testing/tests/client/BridgeIssues/N898.cs
Testing/tests/client/client.csproj
Testing/www/js/bridge.collections.js
Testing/www/js/code.js
Testing/www/js/test.js

https://github.com/bridgedotnet/Bridge/issues/898

Issue898 Decimal assignment in conditional statement fails

---

Compiler/Translator/Emitter/Blocks/IfElseBlock.cs
Testing/tests/client/BridgeIssues/N906.cs
Testing/tests/client/client.csproj
Testing/www/js/code.js
Testing/www/js/test.js

https://github.com/bridgedotnet/Bridge/issues/906

Issue906 Problem with async functions

---

Compiler/Build/GenerateScript.cs
Compiler/Builder/Program.cs
Compiler/Translator/Emitter/Blocks/AsyncBlock.cs
Compiler/TranslatorTests/TestProjects/01/test.csproj
Compiler/TranslatorTests/TestProjects/02/test.csproj
Compiler/TranslatorTests/TestProjects/03/test.csproj
Compiler/TranslatorTests/TestProjects/04/test.csproj
Compiler/TranslatorTests/TestProjects/05/test.csproj
Compiler/TranslatorTests/TestProjects/06/test.csproj
Compiler/TranslatorTests/TestProjects/07/test.csproj
Compiler/TranslatorTests/TestProjects/08/test.csproj
Compiler/TranslatorTests/TestProjects/09/test.csproj
Compiler/TranslatorTests/TestProjects/10/test.csproj
Compiler/TranslatorTests/TestProjects/11/test.csproj
Compiler/TranslatorTests/TestProjects/12/test.csproj
Compiler/TranslatorTests/TestProjects/13/test.csproj
Compiler/TranslatorTests/TestProjects/14/test.csproj
Compiler/TranslatorTests/TestProjects/15/test.csproj
Compiler/TranslatorTests/TestProjects/16/test.csproj
Compiler/TranslatorTests/TestProjects/17/test.csproj
Compiler/TranslatorTests/TestProjects/18/test.csproj
Testing/tests/client/Threading/CancellationTokenTests.cs
Testing/tests/client/Threading/Tasks/AsyncTests.cs
Testing/tests/client/Threading/Tasks/PromiseTests.cs
Testing/tests/client/Threading/Tasks/TaskTests.cs
Testing/tests/client/client.csproj
Testing/tests/clientOne/clientOne.csproj
Testing/tests/typeScriptBridge/typeScriptBridge.csproj
Testing/www/js/code.js
Testing/www/js/test.js

1) Async tests to avoid using `global.setTimeout()`
* repeatability working on diff browsers
* faster
2) Fixes cases when switching on different configurations (Debug/Release) and rebuilding Bridge.sln solution by specifying Configuration for Builder console

Test enhancements

---

Compiler/Contract/IEmitter.cs
Compiler/Translator/Emitter/Blocks/AsyncBlock.cs
Compiler/Translator/Emitter/Blocks/ThrowBlock.cs
Compiler/Translator/Emitter/Blocks/TryCatchBlock.cs
Compiler/Translator/Emitter/Emitter.Properties.cs
Testing/tests/client/BridgeIssues/N928.cs
Testing/tests/client/BridgeIssues/N929.cs
Testing/tests/client/BridgeIssues/N930.cs
Testing/tests/client/client.csproj
Testing/www/js/code.js
Testing/www/js/test.js

https://github.com/bridgedotnet/Bridge/issues/928
https://github.com/bridgedotnet/Bridge/issues/929
https://github.com/bridgedotnet/Bridge/issues/930

Async exceptions [#928] [#929] [#930]

---

Compiler/Translator/Emitter/Blocks/InvocationBlock.cs
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/testIssue434.js
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/testIssue599.js
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/testIssue948.js
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/testIssue948.min.js
Compiler/TranslatorTests/TestProjects/18/TestIssue948.cs
Compiler/TranslatorTests/TestProjects/18/test.csproj

https://github.com/bridgedotnet/Bridge/issues/948

[#948] Check if Script.Write is a comment and do not emit trailing semi-colon

---

Compiler/Translator/Emitter/Emitter.TypeHelpers.cs

https://github.com/bridgedotnet/Bridge/issues/956

[#956] Improve performance for sorting by priority

---

Bridge.sln

[#969] Changes 'Runner' project .NET version to 4.0.

---

Html5/Bridge.Html5.csproj
Html5/Events/TouchEvent.cs
Html5/Interfaces/Touch.cs
Html5/Interfaces/TouchList.cs
Html5/Node/Element.cs

#974
I made this PR to get a feel of the process. This is my first PR for a large project, so I am sorry if I missed something obvious.
I have added `TouchEvent`, `Touch` and `TouchList` per the definitions on [MDN](https://developer.mozilla.org/), and an enumerator for the `TouchList`. I have tested and verified the code in my own environment using my own smartphone. I'm not sure how to setup unit tests for user input like this. I would like some feedback on the following points. 
* Does the file locations make sense?
* I did not split up the `TouchList` and `TouchListEnumerator`, is this a problem?
* Should I be making interfaces enumerable like this and make helper classes like the enumerator?
* I updated the touch event fields in `Element`, is this a problem? I could imagine it might …

[#974] TouchEvent, Touch and TouchList

---

.build/common/CommonAssemblyInfo.cs
.build/common/NuGet.Build.Package.targets
Bridge/System/Runtime.cs

Issue979 Implement [AssemblyInformationalVersion] attribute

---

Bridge/Resources/Collections/List.js
Bridge/System/Collections/Generic/List.cs

List ConvertAll added.

---

Compiler/Translator/Emitter/Emitter.TypeHelpers.cs
Compiler/Translator/Emitter/Emitter.cs

https://github.com/bridgedotnet/Bridge/issues/983

[#983] No Class defined throws Index was out of range build error

---

Compiler/Translator/Emitter/Blocks/MemberReferenceBlock.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/BridgeIssues/1000/N1076.cs
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

Issue1076 [InlineConst] for MaxValue and MinValue prevents from using it as a variable

---

Compiler/Translator/Inspector/Inspector.Visitor.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/BridgeIssues/0800/N857.cs
Tests/Batch1/BridgeIssues/1100/N1120.cs
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

Issue1120 Bridge should not autogenerate default enum values as powers of 2

---

Compiler/Contract/Helpers.cs
Compiler/Translator/Emitter/Blocks/VisitorIndexerBlock.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/BridgeIssues/1000/N1066.cs
Tests/Batch1/BridgeIssues/1000/N1067.cs
Tests/Runner/Batch1/bridge.collections.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

Issue1066 1067

---

Compiler/Translator/Emitter/ArgumentsInfo.cs
Compiler/Translator/Emitter/Blocks/ConstructorBlock.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/BridgeIssues/1000/N1071.cs
Tests/Runner/Batch1/bridge.collections.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

Issue1071 Wrong handling of params Type[]

---

Compiler/Builder/Program.cs

Removes unnecessary leftover prints from Bridge.Builder.exe.

---

Compiler/Translator/Emitter/Blocks/IdentifierBlock.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/BridgeIssues/0600/N637.cs
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

Issue637 Multiname Bug

---

Tests/Batch1/Batch1.csproj
Tests/Batch1/Collections/Generic/StackTests.cs
Tests/Batch1/packages.config
Tests/Runner/Batch1/bridge.collections.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

-  Updates Bridge.Collections to 1.2.1 (after fix #1220)
- Stack tests

Issue1220 Bridge.Collections.1.2.1 update, Stack tests

---

Compiler/Translator/Emitter/Blocks/ConstructorBlock.cs
Compiler/Translator/Emitter/Blocks/ExpressionListBlock.cs
Compiler/Translator/Emitter/Blocks/ObjectCreateBlock.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/BridgeIssues/1200/N1232.cs
Tests/Runner/Batch1/bridge.collections.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

Issue1232 Constructors with "params" behaves incorrectly

---

.build/files/demo.html.pp

[#1234] Use bridge.min.js in demo.html.pp template

---

Html5/Bridge.Html5.csproj
Html5/Elements/MarkElement.cs

Fixes #1241
I haven't included any test coverage as I couldn't get the test projects to build in the repo.

Added MarkElement (Issue #1241)

---

Compiler/Contract/IAbstractEmitterBlock.cs
Compiler/Contract/IWriter.cs
Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.Write.cs
Compiler/Translator/Emitter/Blocks/IdentifierBlock.cs
Compiler/Translator/Emitter/Blocks/IndexerBlock.cs
Compiler/Translator/Emitter/Blocks/InlineArgumentsBlock.cs
Compiler/Translator/Emitter/Blocks/InvocationBlock.cs
Compiler/Translator/Emitter/Blocks/MemberReferenceBlock.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/BridgeIssues/1300/N1343.cs
Tests/Runner/Batch1/bridge.collections.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

Issue1343 Can't compile when using string.Format in GetHashCode method.

---

Bridge/Resources/Console.js
Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/Emitter/Blocks/ArrayCreateBlock.cs
Compiler/Translator/Emitter/Blocks/FieldBlock.cs
Compiler/Translator/Emitter/Blocks/InlineArgumentsBlock.cs
Compiler/Translator/Inspector/Inspector.cs
Compiler/Translator/Utils/RawValue.cs
Compiler/TranslatorTests/TestProjects/01/Bridge/reference/bridge.js
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/test.bridgeIssues.n1023.js
Tests/Batch1/Batch1.csproj
Tests/Batch1/BridgeIssues/1300/N1340.cs
Tests/Runner/Batch1/bridge.collections.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js
Tests/Runner/Batch2/test.js
Tests/Runner/TypeScript/App1/bridge.js
Tests/Runner/TypeScript/App1/generics.js
Tests/Runner/TypeScript/Batch1/5_Generics.js
Tests/TypeScript/Batch1/5_Generics.ts

Issue1340 Generic constructor does not initialize fields and properties

---

Compiler/Translator/Emitter/Blocks/ArrayCreateBlock.cs
Compiler/Translator/Emitter/Blocks/FieldBlock.cs
Compiler/Translator/Emitter/Blocks/InlineArgumentsBlock.cs
Compiler/Translator/Emitter/Blocks/MemberReferenceBlock.cs
Tests/Batch1/BridgeIssues/1300/N1340.cs
Tests/Runner/Batch1/bridge.collections.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

[#1340] Update for the issue, generic array creation

---

Html5/Node/Node.cs

[#1396] Node.TextContent should not be readonly

---

Bridge/System/Delegate.cs

[#1314] Extra semicolons added sometimes and taken away

---

Compiler/Translator/Emitter/ArgumentsInfo.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/BridgeIssues/1300/N1313.cs
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

Issue1313 Interface's default parameters are ignored

---

Html5/Bridge.Html5.csproj
Html5/Events/DragEvent.cs

Add bindings for the DragEvent.
[Drag_and_Drop_API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)
Since Bridge.Test ist not public, there are no new tests.

add DragEvent bindings

---

Compiler/Translator/Emitter/Blocks/BinaryOperatorBlock.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/BridgeIssues/1400/N1429.cs
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

Issue1429 == null ignores == overrides.

---

Compiler/Contract/Constants/CS.cs
Compiler/Contract/Constants/JS.cs
Compiler/Translator/Emitter/Blocks/ConstructorBlock.cs

[#1504] Support of constructor body wrpapping by injectors from plugin

---

Html5/Geolocation/GeolocationCoordinates.cs

Fixes #1474 
Mark non mandatory fields as nullable.

GeolocationCoordinates mark fields as nullable

---

Compiler/Translator/Emitter/Blocks/InvocationBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1700/N1704.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

[#1704] Compilation error when call base method with default arguments

---

Html5/CSS/HTMLColor.cs

Added the following colours:
1. Magenta
2. RebeccaPurple
3. Cyan 
4. LightGrey
5. DimGrey
6. DarkSlateGrey
See Issue #1481.

[1481] Missing HtmlColors

---

Bridge/Bridge/Function.cs
Tests/Batch1/ArgumentsTests.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/Constants.cs
Tests/Batch1/FunctionTests.cs
Tests/Batch1/MixinTests.cs
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

Fixes #1620.
- Fix `Function.Apply` - on client side it should take arguments as an array
- Client tests

[1620] Support of JS Function - fix and test

---

Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1500/N1511.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

Fixes #1511 .
Added client tests.

[1511] Wrong overloaded constructor call with optional parameters - client tests

---

Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1700/N1744.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

Fixes #1744.
Client test added.

[1744] Wrong method invocation with params - client test added

---

Compiler/Translator/Utils/Roslyn/SyntaxHelper.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1802.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[1802] Compiler Exception on @new call

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1803.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[1803] Compiler Exception (Bridge 1.15)

---

Compiler/Contract/Helpers.cs
Compiler/Translator/Emitter/Blocks/MethodBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1804.cs
Tests/Runner/Batch1/code.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[1613] [1804] Struct.$clone() must clone nested structs

---

Compiler/Translator/Utils/Preconverter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1812.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[1812] Compiler Exception (Bridge 1.15)

---

Compiler/Translator/Utils/AssemblyInfo.cs
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/ClientTestHelper/ClientTestHelper.csproj
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/code.js

[1822] CombineScript should force outputBy Project

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1813.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[1813] Compiler Exeption (Bridge 1.15)

---

Compiler/Contract/BridgeType.cs
Compiler/Contract/Helpers.cs
Compiler/Contract/OverloadsCollection.cs
Compiler/Translator/Emitter/Blocks/IndexerBlock.cs
Compiler/Translator/Emitter/Blocks/MemberReferenceBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1821.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

[1821] Missed square brackets in JS (JS syntax error) (v15.0)

---

Compiler/Contract/Helpers.cs
Compiler/Contract/OverloadsCollection.cs
Compiler/Translator/Emitter/Blocks/IndexerBlock.cs
Compiler/Translator/Emitter/Blocks/MemberReferenceBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1834.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[1834] Not defined JavaScript error with [IgnoreGeneric] on interfaces

---

Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.Locals.cs
Compiler/Translator/Emitter/Blocks/ConstructorBlock.cs
Compiler/Translator/Emitter/Blocks/FieldBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1832.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[1832] Invalid JS output on Increment/Decrement static field

---

Compiler/Translator/Emitter/Blocks/EmitBlock.cs
Compiler/Translator/Emitter/Blocks/MemberReferenceBlock.cs
Compiler/Translator/Emitter/TypeScript/EmitBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1000/N1053.cs
Tests/Batch3/BridgeIssues/1800/N1848.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[1848] FieldProperty in the interface generates incorrect name

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Compiler/Contract/BridgeType.cs
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1850.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[1850] Runtime error when class explicitly implements interface method

---

Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1856.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

Fixes #1856 
Unit test only because the fix was provided in another pull request

[1856] <...> is not a function error (unit test only)

---

.gitignore
Bridge/Resources/.generated/bridge.js
Bridge/Resources/Class.js
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1869.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

[1869] Generic type definition should be shared (not type with arguments)

---

.gitignore
Compiler/Contract/XmlToJsDoc.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1871.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

[1871] Error comment throws compiler exception

---

.gitignore
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1872.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

[1872] async with anonymous delegate

---

.gitignore
Compiler/Translator/Emitter/Blocks/ConversionBlock.Number.cs
Compiler/Translator/Emitter/Blocks/IndexerBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1875.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

[1875] Dictionary with long variable as key is set incorrectly

---

Compiler/Translator/Emitter/Blocks/InlineArgumentsBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1880.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

[1880] Default values with templates don't work

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/.generated/bridge/utils/console.js
Compiler/Translator/Emitter/Blocks/ForeachBlock.cs
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1882.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

[1882] External class generate invalid name cast in loop

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/Runner/Batch1/bridge.js

Fixes #1889 
IE10 doesn't support `Uint8ClampedArray` therefore Bridge should check it

[1889] Bridge throws exception in IE10

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Date.js
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/Batch1/SimpleTypes/JsDateTests.cs
Tests/Batch3/BridgeIssues/0500/N582.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/TypeScript/Batch1/0_Issues.js
Tests/Runner/TypeScript/Batch1/1_BasicTypes.js
Tests/Runner/TypeScript/Batch1/2_Interfaces.js
Tests/Runner/TypeScript/Batch1/3_Classes.js
Tests/Runner/TypeScript/Batch1/4_Functions.js
Tests/Runner/TypeScript/Batch1/5_Generics.js

[1901] DateTime to Timestamp back to DateTime is different

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Integer.js
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1896.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[1896] Parse/TryParse not support hex string

---

Compiler/Contract/OverloadsCollection.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1899.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js
Tests/Runner/TypeScript/App1/interfaces.js
Tests/Runner/TypeScript/Batch1/0_Issues.js
Tests/Runner/TypeScript/Batch1/1_BasicTypes.js
Tests/Runner/TypeScript/Batch1/2_Interfaces.js
Tests/Runner/TypeScript/Batch1/3_Classes.js
Tests/Runner/TypeScript/Batch1/4_Functions.js
Tests/Runner/TypeScript/Batch1/5_Generics.js
Tests/TypeScript/Batch1/2_Interfaces.ts

[1899] Generated property getter name conflicts with other function name

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Integer.js
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1900/N1933.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

[1933] Incorrect rounding with Decimal 

---

Html5/Interfaces/CanvasRenderingContext2D.cs

[1917] HtmlCanvas StrokeStyle & FillStyle can accept gradient and pattern

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Bridge/Resources/Date.js
Bridge/Resources/Nullable.js
Bridge/Resources/TimeSpan.js
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/Runner/Batch1/bridge.js

[1907] Modify Bridge.hasValue to accept multiple arguments

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Collections/Dictionary.js
Bridge/Resources/Core.js
Bridge/System/Collections/Generic/IEnumerable.cs
Compiler/Translator/Emitter/Blocks/ForeachBlock.cs
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1900/N1996.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch2/code.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[1996] Template for IEnumerable.GetEnumerator is ignored

---

Compiler/Contract/XmlToJsDoc.cs
Compiler/Translator/Emitter/Blocks/VisitorIndexerBlock.cs
Compiler/Translator/Emitter/TypeScript/IndexerBlock.cs
Compiler/Translator/Emitter/TypeScript/MemberBlock.cs
Compiler/TranslatorTests/TestProjects/07/Bridge/reference/testProject.issues.js
Compiler/TranslatorTests/TestProjects/07/Bridge/reference/testProject.issues.min.js
Compiler/TranslatorTests/TestProjects/07/Bridge/reference/testProject1.js
Compiler/TranslatorTests/TestProjects/07/Issues/N2007.cs
Compiler/TranslatorTests/TestProjects/07/test.csproj
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/code.js

[2007] Javascript generated comments for event

---

Compiler/Contract/BridgeType.cs
Compiler/Contract/IEmitter.cs
Compiler/Contract/OverloadsCollection.cs
Compiler/Translator/Emitter/Blocks/ClassBlock.cs
Compiler/Translator/Emitter/Blocks/EmitBlock.cs
Compiler/Translator/Emitter/Emitter.Helpers.cs
Compiler/Translator/Emitter/Emitter.Properties.cs
Compiler/Translator/Emitter/Emitter.TypeHelpers.cs
Compiler/Translator/Translator/Translator.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Runner/Batch1/code.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/code.js

[1902] Very long compilation time on big projects

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Compiler/Translator/Utils/Roslyn/SyntaxHelper.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2024.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

[2024] "using static" fails to access enum in another class

---

Compiler/Translator/Inspector/Inspector.Visitor.cs
Compiler/TranslatorTests/OutputTest.cs
Compiler/TranslatorTests/TestProjects/06/Bridge/bridge.json
Compiler/TranslatorTests/TestProjects/06/Properties/AssemblyInfo.cs

[1963] Bridge.OutputByAttribute doesn't have an effect

---

Compiler/Translator/Emitter/Blocks/InlineArgumentsBlock.cs
PostBuild/readme.md
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2027.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2027] ToString fails for enum values when concatenating with another string

---

Compiler/Contract/Helpers.cs
Compiler/Translator/Emitter/Blocks/FieldBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2033.cs
Tests/Runner/Batch1/code.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2033] Enum class variables not initialised properly

---

Bridge/Resources/.auxiliary/Header.js
Bridge/Resources/.generated/bridge.js
Bridge/Resources/.typescript/header.d.ts
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Compiler/TranslatorTests/TestProjects/11/Bridge/reference/bridge.d.ts
Tests/Runner/Batch1/bridge.js

- Bump release date for 15.4.0 -> 2016-11-08

Bump release date for 15.4.0

---

Compiler/Translator/Emitter/Blocks/AssignmentBlock.cs
Compiler/Translator/Emitter/Blocks/MethodBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2038.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2038] Invalid javascript for "this += 1" in structs

---

Html5/Elements/HTMLBodyElement.cs
Html5/ErrorEventHandler.cs
Html5/Global.cs
Html5/Window.cs
Html5/WindowInstance.cs

Fixed #2034: Window.OnError wrong arguments.

Fixed #2034: Window.OnError wrong arguments.

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2045.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2045] Double Escaping / Incorrect Escaping in String Interpolation

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2046.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2046] Safe navigation operator .? on nullable DateTime

---

Compiler/Translator/Emitter/Blocks/UnaryOperatorBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2048.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2048] Compilation error

---

Bridge/Bridge/Console/Console.cs
Bridge/Resources/.generated/bridge.js
Bridge/Resources/.generated/bridge/utils/console.js
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/Runner/Batch1/bridge.js

Preserve whitespaces in Bridge Console

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Integer.js
Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2039.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2039] Incorrect double.NaN.ToString() value

---

Bridge/System/AppDomain.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2042.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2042] System.AppDomain.getCurrentDomain is not a function

---

Compiler/Translator/Emitter/Blocks/BinaryOperatorBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2073.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2073] Invalid implicit operator call

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2079.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2079] LINQ expression causes compiler exception

---

Compiler/Translator/Emitter/Blocks/AssignmentBlock.cs
Compiler/Translator/Emitter/Blocks/IdentifierBlock.cs
Compiler/Translator/Emitter/Blocks/MemberReferenceBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2080.cs
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2080] OR assignment operator causes compilation failure when used with class properties

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/linq.js
Compiler/Translator/Emitter/Blocks/LambdaBlock.cs
Gruntfile.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1800/N1848.cs
Tests/Batch3/BridgeIssues/2000/N2076.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js
appveyor.yml

[2076] Javascript Global Namespace Pollution for linq.js

---

Bridge/Bridge.csproj
Bridge/Resources/.generated/bridge.js
Bridge/Resources/Attribute.js
Bridge/System/Attribute.cs
Bridge/System/Reflection/MemberInfo.cs
Bridge/System/Reflection/ParameterInfo.cs
Bridge/System/Runtime.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/Reflection/AssemblyAttributesDefinition.cs
Tests/Batch1/Reflection/AssemblyTests.cs
Tests/Batch1/Reflection/AttributeTests.cs
Tests/Batch1/Reflection/TypeAttributeTests.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js
Tests/Runner/Batch4/code.js

Addressed #2043.
**Implemented in this Pull Request**:
| Name | Description |
| --- | --- |
| [GetCustomAttributes(Assembly)](https://msdn.microsoft.com/en-us/library/y1375e30(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to an assembly. A parameter specifies the assembly. | 
| [GetCustomAttributes(Assembly, Boolean)](https://msdn.microsoft.com/en-us/library/f2z5sd1c(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to an assembly. Parameters specify the assembly, and an ignored search option. | 
| [GetCustomAttributes(Assembly, Type)](https://msdn.microsoft.com/en-us/library/4ske1977(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to an assembly. Parameters specify the assembly, and the type of the custom attribute to …

[2043] Implement Attribute.GetCustomAttributes

---

Html5/Events/AnimationEvent.cs
Html5/Events/CompositionEvent.cs
Html5/Events/CustomEvent.cs
Html5/Events/DragEvent.cs
Html5/Events/FocusEvent.cs
Html5/Events/HashChangeEvent.cs
Html5/Events/KeyboardEvent.cs
Html5/Events/MouseEvent.cs
Html5/Events/TouchEvent.cs
Html5/Events/WheelEvent.cs
Tests/Runner/Batch1/Bridge.Test/themes/north/css/main.css
Tests/Runner/Batch1/Bridge.Test/themes/north/js/main.js
Tests/Runner/Batch1/test.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js

[2205] MouseEvent<T> does not inherit MouseEvent

---

Bridge/Bridge/Console/Console.cs
Bridge/Resources/.generated/bridge.js
Bridge/Resources/.generated/bridge/utils/console.js
Tests/Batch1/BridgeConsoleTests.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2100/N2186.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js

[2186] Calling Console.WriteLine() should write blank line in Bridge.Console 

---

Html5/Bridge.Html5.csproj
Html5/DOMParser.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/DOMParserTests.cs
Tests/Runner/Batch1/code.js
Tests/Runner/Batch1/test.js

[1728] Support for DOMParser

---

Bridge/Bridge.csproj
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2100/N2192.cs
Tests/Runner/Batch1/test.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch3/test.js
Tests/Runner/Batch4/code.js
appveyor.yml

Fixes #2192
Adds 100 `Intersection<T1, T2, ..., T100>` types.

[2192] Intersection type

---

Bridge/System/Threading/Thread.cs

[2271] Remove EditorBrowsable attribute from System.Threading.Thread class

---

Bridge/Bridge.csproj
Bridge/System/SerializableAttribute.cs
Compiler/Contract/AttributeHelper.cs
Compiler/Contract/Constants/CS.cs

[2274] Basic support for [Serializable] attribute

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/linq.js
Bridge/System/Linq/Lookup.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2300/N2355.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2355] Linq interfaces have no definitions in javascript

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/.generated/system/random.js
Compiler/Translator/Emitter/Blocks/ParenthesizedBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2300/N2342.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2342] Incorrect precedence of operations in expressions with casts

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Nullable.js
Bridge/System/Nullable.cs
Compiler/Translator/Emitter/Blocks/GeneratorBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2000/N2049.cs
Tests/Batch3/BridgeIssues/2300/N2359.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2049] Support Nullable.GetUnderlyingType(Type type)

---

Compiler/Translator/Emitter/Blocks/UnaryOperatorBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2300/N2352.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2352] Compilation fails if Anonymous type with bool field is used with ! unary operator

---

.build/packages/collect.bat
.gitignore
Bridge.sln
Compiler/Builder/Bridge.Builder.csproj
Compiler/Builder/Properties/AssemblyInfo.cs
Compiler/TranslatorTests/TestProjects/02/test.csproj
Compiler/TranslatorTests/TestProjects/03/test.csproj
Compiler/TranslatorTests/TestProjects/04/test.csproj
Compiler/TranslatorTests/TestProjects/05/test.csproj
Compiler/TranslatorTests/TestProjects/06/test.csproj
Compiler/TranslatorTests/TestProjects/07/test.csproj
Compiler/TranslatorTests/TestProjects/10/test.csproj
Compiler/TranslatorTests/TestProjects/11/test.csproj
Compiler/TranslatorTests/TestProjects/15/test.csproj
Compiler/TranslatorTests/TestProjects/16/test.csproj
Compiler/TranslatorTests/TestProjects/18/test.csproj
Compiler/TranslatorTests/TestProjects/19/test.csproj
PostBuild/Bridge.PostBuild.csproj
Tests/Batch1/Batch1.csproj
Tests/Batch2/Batch2.csproj
Tests/Batch3/Batch3.csproj
Tests/Batch4/Batch4.csproj
Tests/ClientTestHelper/ClientTestHelper.csproj
Tests/ClientTestHelperExternal/ClientTestHelperExternal.csproj
Tests/TypeScript/App1/App1.csproj

[2175] Rename Bridge.Builder.exe to bridge.exe

---

Compiler/Translator/Emitter/Blocks/FieldBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2300/N2374.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2374] DateTime AutoProperty and Initializer not being emitted correctly

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Tests/Runner/Batch1/bridge.js

Fixes #2435.
- Original time: aprx. 90ms
- Improved time: aprx. 40ms

[2435] Improve performance of Bridge.getTypeAlias

---

Bridge/System/Collections/Generic/List.cs

[2422] RemoveRange has wrong return type.

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Array.js
Compiler/Translator/Utils/CaptureAnalyzer.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2400/N2469.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2469] Generic argument is unknown in a lambda method used in a generic class

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/.generated/system/bitConverter.js
Bridge/Resources/.generated/system/formattableStringImpl.js
Bridge/Resources/.generated/system/guid.js
Bridge/Resources/.generated/system/random.js
Bridge/Resources/.generated/system/version.js
Bridge/Resources/Array.js
Compiler/Contract/Constants/JS.cs
Compiler/Translator/Emitter/Blocks/IndexerBlock.cs
Compiler/TranslatorTests/TestProjects/05/Bridge/reference/test.bridgeIssues.n772.js
Compiler/TranslatorTests/TestProjects/06/Bridge/reference/test.js
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/test.bridgeIssues.n089.js
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/test.bridgeIssues.n2318.js
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/test.bridgeIssues.n524.js
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/test.bridgeIssues.n694.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/0100/N156.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/Bridge.Test/main.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch2/code.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/code.js
Tests/Runner/TypeScript/App1/functions.js

[156] 1D array does not throw exception when referenced outside its boundaries

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2400/N2456.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2456] JS array passed across frames isn't recognized as an array by Bridge

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Exception.js
Bridge/System/Exception.cs
Tests/Batch1/BasicCSharp/TestTryCatchBlocks.cs
Tests/Batch1/BasicCSharp/TestTryCatchFinallyBlocks.cs
Tests/Batch1/Exceptions/DivideByZeroExceptionTests.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2400/N2458.cs
Tests/Batch4/Exceptions/DivideByZeroExceptionTests.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/code.js

[2458] Add support for Exception.GetBaseException()

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Text/StringBuilder.js
Compiler/Translator/Emitter/Blocks/DoWhileBlock.cs
Compiler/Translator/Emitter/Blocks/ForBlock.cs
Compiler/Translator/Emitter/Blocks/ForeachBlock.cs
Compiler/Translator/Emitter/Blocks/SwitchBlock.cs
Compiler/Translator/Emitter/Blocks/WhileBlock.cs
Tests/Batch1/Text/StringBuilderTests.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2500/N2502.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2502] Break/Continue incorrect behaviour inside async methods

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/BridgeIssues/2400/N2497.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2497] Additional possible fix

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Long.js
Tests/Batch1/SimpleTypes/UInt64Tests.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2500/N2505.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2505] Error - Casting Ulong, Bit shifting or adding values.

---

.build/specs/Bridge.Compiler.Mono.nuspec
.build/specs/Bridge.Compiler.nuspec
.build/specs/Bridge.Contract.Mono.nuspec
.build/specs/Bridge.Contract.nuspec
Compiler/Contract/Bridge.Contract.csproj
Compiler/Contract/packages.config
Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/packages.config
appveyor.yml
packages/repositories.config

[2495] Upgrade projects to Json.NET 10.0.1

---

Bridge/Bridge/Sequence.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2400/N2460.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

Fixes #2460
- **sealed** modifier was removed
- **Sequence** types were marked with `[IgnoreGeneric]` attribute

[2460] Sequence type inheritance

---

Compiler/Builder/Program.cs
Compiler/Translator/Translator/Translator.cs
Compiler/Translator/Translator/TranslatorProcessor.cs
Compiler/TranslatorTests/BuilderTests/BuilderTests.cs

[2519] Two JavaScript files are generated in Folder (Lib) mode

---

Html5/Interfaces/Types/CanvasCompositeOperationType.cs

[2546] CanvasTypes.CanvasCompositeOperationType.DestinationAtop missing dash

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Class.js
Bridge/Resources/Core.js
Tests/Runner/Batch1/bridge.js

Required fixes for aspects

---

Tests/Batch1/Collections/Generic/IteratorBlockTests.cs
Tests/Batch1/Format/DateTimeFormatInfoTests.cs
Tests/Batch1/SimpleTypes/EnumTests.cs
Tests/Batch1/SimpleTypes/UInt64Tests.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/code.js

Ensures tests for:
* #1554
* #1562
* #1591
* #1596

Portarelle tests review

---

Compiler/Translator/Emitter/Blocks/ObjectCreateBlock.cs
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/testIssue2141.js
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/testIssue379.js
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/testResources1.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2600/N2635.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/code.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/code.js

[2635] Nested object create initialization is failed

---

Bridge/Bridge/Console/Console.cs
Bridge/Resources/.generated/bridge.js
Bridge/Resources/.generated/bridge/utils/console.js
Bridge/Resources/Core.js
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js

[2663] Bridge Console Error Logging Exception

---

Compiler/Contract/Helpers.cs
Compiler/Translator/Emitter/Blocks/IndexerBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2600/N2671.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2671] IDictionary indexer generates invalid script

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Class.js
Tests/Runner/Batch1/bridge.js

[2666] Additional fix for IE11

---

Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.Locals.cs
Compiler/Translator/Emitter/Blocks/ForeachBlock.cs
Compiler/Translator/Emitter/Blocks/LambdaBlock.cs
Compiler/Translator/Emitter/Blocks/ThrowBlock.cs
Compiler/Translator/Emitter/Blocks/TryCatchBlock.cs
Compiler/Translator/Utils/LoopVariablesAnalyzer.cs
Compiler/Translator/Utils/ReferenceArgumentVisitor.cs
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/test.bridgeIssues.n1508.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2600/N2686.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2686] Incorrect function parameter is captured by lambda

---

Compiler/Translator/Utils/TypeInfo.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2600/N2685.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2685] The order of partial class implementations seems to affect what properties are defined on the target object

---

Compiler/Translator/Emitter/Emitter.Visitor.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2600/N2692.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2692] Unused labels crash compiler

---

Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.Write.cs
Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.cs
Compiler/Translator/Emitter/Blocks/BinaryOperatorBlock.cs
Compiler/Translator/Emitter/Blocks/ConditionalBlock.cs
Compiler/Translator/Emitter/Blocks/ExpressionBlock.cs
Compiler/Translator/Utils/AwaitSearchVisitor.cs
Compiler/Translator/Utils/Preconverter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2600/N2689.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2689] Problems with question mark operator with async

---

Html5/Ajax/XMLHttpRequestEventTarget.cs
Html5/CSS/CSSStyleDeclaration.cs
Html5/Document.cs
Html5/DocumentInstance.cs
Html5/Elements/HTMLElement.cs

Revisions to support #2702 and #2729

Html5fixes

---

Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.Locals.cs
Compiler/Translator/Emitter/Blocks/ConstructorBlock.cs
Compiler/Translator/Emitter/Blocks/FieldBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2700/N2745.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2745] Field initialization doesn't emit temp variables

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/.generated/bridge/utils/console.js
Bridge/Resources/.generated/system/console.js
Bridge/System/Object.cs
Compiler/Translator/Emitter/Blocks/ConversionBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2700/N2749.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/Bridge.Test/main.js
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/code.js

[2749] As<> method should prevent boxing operation

---

Compiler/Translator/Emitter/Emitter.TypeHelpers.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2700/N2759.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2759] Error occurs when class has where constraints for types not yet defined in document

---

Bridge/Bridge/Script.cs
Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/Emitter/Blocks/AsyncBlock.cs
Compiler/Translator/Utils/Roslyn/AwaitersCollector.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2700/N2763.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2763] Creating await lists fails with weird error.

---

Compiler/Contract/Helpers.cs
Compiler/Contract/Name/Semantic.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2700/N2764.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2764] External classes marked with [Namespace] and [IgnoreGeneric]

---

Html5/CSS/CSSStyleDeclaration.cs

[2799] Convert all Enum fields to Union<string, Enum> types in CSSStyleDeclaration of Bridge.Html5

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Compiler/Translator/Emitter/Blocks/ObjectCreateBlock.cs
Compiler/Translator/Inspector/Validator.cs
Compiler/TranslatorTests/CompilerTests/ValidatorTests.cs
Tests/Batch3/BridgeIssues/2700/N2795.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

Addresses #2795 (fixes a problem introduced in #2803)

[2795] Additional fix

---

Compiler/Translator/Emitter/Blocks/FieldBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2800/N2844.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2844] Property initialization is failed

---

Html5/Elements/Element.cs

[2854] OuterHTML should not be readonly.

---

Bridge/Bridge/This.cs

[2864] Bridge.This.Instance to return object

---

Compiler/Contract/Bridge.Contract.csproj
Compiler/Contract/Config/ConsoleConfig.cs
Compiler/Contract/Config/IAssemblyInfo.cs
Compiler/Translator/Translator/Translator.Resources.cs
Compiler/Translator/Utils/AssemblyInfo.cs
Compiler/TranslatorTests/CompilerTests/AssemblyInfoJsonConvertersTests.cs
Compiler/TranslatorTests/CompilerTests/AssemblyInfoTests.cs
Compiler/TranslatorTests/TestProjects/04/Bridge/bridge.json
Compiler/TranslatorTests/TestProjects/04/Bridge/reference/index.html
Compiler/TranslatorTests/TestProjects/06/Bridge/bridge.json
Compiler/TranslatorTests/TestProjects/06/Bridge/reference/index.html

Fixes #2851 
```json
{
"console": {
"disabled": true
}
}
```
Alternative syntax:
```json
{
"console": false
}
```

[2851] New console config for bridge.json and tests

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Bridge/System/Delegate.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2900/N2903.cs
Tests/Batch3/BridgeIssues/2900/N2904.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/code.js

[2903] Exception in Contains for GetInvocationList() collection.
[2904] Any on GetInvocationList() collection works wrong.
Fixes #2903 and #2904

[2903] Exception in Contains for GetInvocationList() collection.

---

Html5/Elements/HTMLElement.cs
Html5/Elements/HTMLMediaElement.cs
Html5/Elements/HTMLTableCellElement.cs
Html5/Elements/MarkElement.cs
Html5/Events/AnimationEvent.cs
Html5/Events/CompositionEvent.cs
Html5/Events/CustomEvent.cs
Html5/Events/DragEvent.cs
Html5/Events/Event.cs
Html5/Events/FocusEvent.cs
Html5/Events/HashChangeEvent.cs
Html5/Events/KeyboardEvent.cs
Html5/Events/MouseEvent.cs
Html5/Events/ProgressEvent.cs
Html5/Events/TouchEvent.cs
Html5/Events/UIEvent.cs
Html5/Events/WheelEvent.cs
Html5/Node/HTMLCollection.cs
Html5/TypedArray/Prototype.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2900/N2904.cs
Tests/Batch3/BridgeIssues/2900/N2911.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js
Tests/Runner/TypeScript/App1/typeScript.issues.d.ts
Tests/Runner/TypeScript/App1/typeScript.issues.js
Tests/Runner/TypeScript/Batch1/0_Issues.js
Tests/TypeScript/App1/App1.csproj
Tests/TypeScript/App1/Issues/N2911.cs
Tests/TypeScript/Batch1/0_Issues.ts

[2911] Html generic classes should have [IgnoreGeneric]

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/.generated/system/console.js
Bridge/System/Console.cs
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/bridge.report.log
Tests/Runner/Batch1/bridge.js

[2974] empty Console.WriteLine() returns undefined in browser console

---

.appveyor.yml
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/bridge.report.log

https://appveyor.statuspage.io/incidents/m2vdvw39kdk8

Remove temp workaround for AppVeyor

---

Compiler/Contract/TranslatorOutput.cs
Compiler/Translator/Translator/Translator.Output.cs

Fix exception when combining and outputs from referenced assemblies

---

Compiler/Translator/Properties/AssemblyInfo.cs
Compiler/Translator/Translator/Translator.Output.cs
Compiler/TranslatorTests/Bridge.Translator.Tests.csproj
Compiler/TranslatorTests/CompilerTests/CombineTests.cs

[3039] Combine scripts throws NullReferenceException in 16.0.1

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Globalization.js
Tests/Batch1/CultureInfoTests.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch1/code.js

[2583] CultureInfo constructor and GetCultureInfo inconsistencies

---

README.md

Master up to 4ef29b6 into v16.1

Master up to 4ef29b6 into v16.1

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Tests/Batch1/SimpleTypes/DateTimeTests.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/bridge.js

[3098] DateTime equals does not compare Ticks

---

Compiler/Translator/Emitter/Blocks/ParenthesizedBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3100/N3158.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3158] Invalid code emit in Parenthesized Block

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs

[3211] BabylonJS demo is not compiled with Bridge 16.4

---

Compiler/Translator/Emitter/Blocks/ConstructorBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3200/N3231.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch2/Bridge.Test/bridge.clienttest.batch2.runner.js
Tests/Runner/Batch2/code.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/Bridge.Test/bridge.clienttest.batch4.runner.js
Tests/Runner/Batch4/code.js
Tests/Runner/ClientTestHelper/code.js
Tests/Runner/TypeScript/App1/basicTypes.js
Tests/Runner/TypeScript/App1/bridge.d.ts

[3231] ObjectLiteral incorrectly emits $getType function

---

Compiler/Contract/Helpers.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3200/N3242.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3242] Implicit operator bypassed for [ObjectLiteral] types

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Collections/Interfaces.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3200/N3244.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3244] Lists aren't IEnumerable of implementing generic types

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3200/N3222.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3222] Array becomes not equal to itself

---

Compiler/Translator/Emitter/Blocks/InlineArgumentsBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3200/N3226.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3226] += does not work on multi-dim arrays in some situtations.

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/TimeSpan.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3200/N3249.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3249] TimeSpan.Equals throws when passed value

---

Compiler/Translator/Inspector/Validator.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3200/N3251.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3251] ObjectCreateMode.Constructor) with struct fails

---

Bridge/Resources/.generated/bridge.js
Compiler/Translator/Emitter/Blocks/ConversionBlock.cs
Compiler/Translator/Emitter/Blocks/UnaryOperatorBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3200/N3258.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3258] Missing unary operator with Template implicit operator

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3200/N3264.cs
Tests/Batch3/BridgeIssues/3200/N3265.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3264] Type aliases for generic types do not work

---

Compiler/Translator/Emitter/TypeScript/MethodsBlock.cs
Compiler/TranslatorTests/IntegrationTests/IntegrationTest.cs
Compiler/TranslatorTests/TestProjects/11/Bridge/reference/Issue3278.d.ts
Compiler/TranslatorTests/TestProjects/11/Bridge/reference/Issue3278.js
Compiler/TranslatorTests/TestProjects/11/Bridge/reference/TestProject.meta.js
Compiler/TranslatorTests/TestProjects/11/Bridge/reference/bridge.report.log
Compiler/TranslatorTests/TestProjects/11/Bridge/reference/index.html
Compiler/TranslatorTests/TestProjects/11/Issues/N3278.cs
Compiler/TranslatorTests/TestProjects/11/test.csproj

[3278] autoProperty: Plain causes double write of props in .d.ts

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Tests/Runner/Batch1/bridge.js

Fixes #3285 
Improve performance of System.DateTime.$is

[3285] Replace Syste.DateTime.$is code to improve performance

---

Compiler/Translator/Translator/Translator.cs
Compiler/Translator/Utils/Preconverter.cs
Tests/Runner/Batch3/code.js

It is not fix for #3284 but changes in this PR will help us to identify similar problems in future

[3284] Add some diagnostic code to help identify source of such issues

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Date.js
Tests/Runner/Batch1/bridge.js

[3285] Remove date cast in compare functions

---

Compiler/Contract/Bridge.Contract.csproj
Compiler/Contract/packages.config
Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/packages.config
Compiler/TranslatorTests/Bridge.Translator.Tests.csproj
Compiler/TranslatorTests/packages.config
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3200/N3292.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

Fixes #3292 .
- Update bridge references to NRefactory 5.5.9
- Add unit test for the specific issue (pending)

[3292] Updates necessary to fix issue

---

Compiler/Build/GenerateScript.cs
Compiler/Build/VSLoggerWriter.cs
Compiler/Contract/ILogger.cs
Compiler/Translator/Logging/ConsoleLoggerWriter.cs
Compiler/Translator/Logging/FileLoggerWriter.cs
Compiler/Translator/Logging/Logger.cs

Fixes #3297 .
- Correct message for errors originated from Plugins.
- Avoid duplicated messages.

[3297] Exceptions originated from plugins

---

Compiler/Translator/Translator/Translator.cs

Fixes #3259.
- Builds a simpler dependency graph for topological sorting

Simplified SortReferences()

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/TimeSpan.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3300/N3352.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3352] TimeSpan? is compared wrong with null

---

Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/Utils/Roslyn/ChainingAssigmentReplacer.cs
Compiler/Translator/Utils/Roslyn/ICSharpReplacer.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Compiler/Translator/Utils/Roslyn/SyntaxHelper.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2800/N2872.cs
Tests/Batch3/BridgeIssues/3300/N3390.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2872] Chaining assigment with the same variable gets illegal JS

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Array.js
Compiler/Translator/Emitter/Blocks/ArrayCreateBlock.cs
Compiler/Translator/Inspector/Inspector.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3300/N3396.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3396] Writing to multidimensional array overwrites all

---

Compiler/Translator/Emitter/Blocks/ConstructorBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3300/N3382.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3382] Incorrect constructor is called (params use case)

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Convert.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3300/N3385.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3385] Convert.ToChar fails when converting from object

---

Compiler/Translator/Emitter/Blocks/InlineArgumentsBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3400/N3426.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3426] GetType() returns the wrong value when calling inherited methods

---

Compiler/Translator/Inspector/Inspector.Visitor.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3400/N3432.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3432] Issue with derivation and explicit interface implementation.

---

Bridge/Attributes/RulesAttribute.cs
Compiler/Contract/Rule/Rules.cs
Compiler/Translator/Emitter/Blocks/CommentBlock.cs

Adds InlineComment rule support

---

Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/Utils/Roslyn/IsPatternReplacer.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Compiler/Translator/Utils/Roslyn/SwitchPatternReplacer.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/CSharp7/TestCaseLabelPattern.cs
Tests/Batch1/CSharp7/TestIsPattern.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js

c$7 "is" and switch case patterns

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/CSharp7/TestROStruct.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js

This rebases #3456 onto Bridge v17.

c# 7.2 read only struct support

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Compiler/Translator/Utils/Roslyn/SyntaxHelper.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/CSharp6/TestExpressionBodyFunction.cs
Tests/Batch1/CSharp7/TestExpressionBodyMember.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js

V17 c sharp7 expression body

---

Bridge/Attributes/UnboxAttribute.cs
Bridge/Bridge.csproj
Bridge/Bridge/Script.cs
Bridge/Resources/Collections/KeyValuePair.js
Bridge/Resources/Core.js
Bridge/System/Collections/Generic/KeyValuePair.cs
Bridge/System/Runtime.cs
Bridge/System/Tuple.cs
Bridge/System/ValueTuple.cs
Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/Utils/Roslyn/DeconstructionReplacer.cs
Compiler/Translator/Utils/Roslyn/DiscardReplacer.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Compiler/Translator/Utils/Roslyn/SyntaxHelper.cs
Compiler/Translator/packages.config
Tests/Batch1/Batch1.csproj
Tests/Batch1/CSharp7/TestDefaultLiteralExpression.cs
Tests/Batch1/CSharp7/TestDiscardsAndOutVars.cs
Tests/Batch1/CSharp7/TestThrowExpression.cs
Tests/Batch1/CSharp7/TestValueTupleAndDeconstruction.cs

Implements various C#7 features.
This was manually pulled out of the #3469 pull request into a working bridge 17 git tree.
Initially the branch has been pushed without committing the files that bridge generates by itself during build time, for easier review.
This is the cleanest view of the feature code, with minimal NuGet updates within the projects (just the necessary in order for the features to work).
All tests runs fine at this point.

C#7's ValueTuple + Throw Expressions + Discards + Out vars - merged to Bridge 17.

---

Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/Utils/Roslyn/LocalFunctionReplacer.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/CSharp7/TestLocalFunctions.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js

C#7 Local functions support

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Task.js
Tests/Batch1/MutationObserverTests.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3400/N3476.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3476] HUGE DESIGN FLAW with async Task / runCallbacks

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Bridge/Resources/Task.js
Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.cs
Tests/Runner/Batch1/bridge.js

Fixes another case raised within #3467 after previous fix was sent.

[3467] Design flaw with async Task / runCallbacks (another test case)

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Collections/Interfaces.js
Compiler/TranslatorTests/TestProjects/04/Bridge/reference/reports/bridge.report.custom.log
Compiler/TranslatorTests/TestProjects/05/Bridge/reference/bridge.report.log
Compiler/TranslatorTests/TestProjects/06/Bridge/reference/report.log
Compiler/TranslatorTests/TestProjects/07/Bridge/reference/reports/report.log
Compiler/TranslatorTests/TestProjects/08/Bridge/reference/bridge.report.custom.name.log
Compiler/TranslatorTests/TestProjects/10/Bridge/reference/bridge.report.log
Compiler/TranslatorTests/TestProjects/11/Bridge/reference/bridge.report.log
Compiler/TranslatorTests/TestProjects/15/Bridge/reference/bridge.report.log
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/bridge.report.log
Compiler/TranslatorTests/TestProjects/19/Bridge/reference/bridge.report.log
Compiler/TranslatorTests/TestProjects/20/Bridge/reference/reports/bridge.report.log
Compiler/TranslatorTests/TestProjects/22/Bridge/reference/reports/bridge.report.log
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3500/N3502.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3502] Casting error/bug - May relate to invariance

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Compiler/Contract/IValidator.cs
Compiler/Translator/Emitter/Blocks/AssignmentBlock.cs
Compiler/Translator/Emitter/Blocks/BaseReferenceBlock.cs
Compiler/Translator/Inspector/Validator.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3400/N3485.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3485] Virtual properties in external classes

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Class.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3400/N3494.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3494] Inheritors of an external class call the base ctor improperly

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Collections/Dictionary.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3400/N3499.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3499] Dictionary.Values crashes

---

Compiler/Translator/Utils/Roslyn/LocalFunctionReplacer.cs
Tests/Batch1/CSharp7/TestLocalFunctions.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js

Support arrow local functions

---

Bridge/Attributes/PrivateProtectedAttribute.cs
Bridge/Bridge.csproj
Bridge/System/Reflection/MemberInfo.cs
Compiler/Translator/Utils/MetadataUtils.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch1/Batch1.csproj
Tests/Batch1/CSharp7/TestPrivateProtected.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js

[3491] C# 7 private protected access modifier

---

Bridge/Attributes/RulesAttribute.cs
Compiler/Contract/Rule/Rules.cs
Compiler/Translator/Emitter/Blocks/CastBlock.cs
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/TestIssue3516.js
Compiler/TranslatorTests/TestProjects/18/Bridge/reference/TestProject.meta.js
Compiler/TranslatorTests/TestProjects/18/Issues/Issue3516.cs
Compiler/TranslatorTests/TestProjects/18/test.csproj
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3500/N3516.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3516] New ExternalCast Rule

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Double.js
Compiler/Translator/Utils/Roslyn/IsPatternReplacer.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Compiler/Translator/Utils/Roslyn/SwitchPatternReplacer.cs
Tests/Batch1/CSharp7/TestCaseLabelPattern.cs
Tests/Batch1/CSharp7/TestIsPattern.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/code.js

Support var keywords in case patterns

ConstantPatternSyntax support

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Class.js
Bridge/Resources/Core.js
Tests/Runner/Batch1/bridge.js

[3511] IE11 error while accessing via interface

---

.build/files/bridge.json

Review default bridge.json file and add new rules

---

Compiler/Translator/Utils/Roslyn/LocalFunctionReplacer.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3500/N3560.cs
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

Also Fix the case https://deck.net/3e5ea1c0028d0dadc7687e84da7ac16f
Fixes #3560
-

[3560] UnknownIdentifierResolveResult in self-referencing local function

---

Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/Translator/Translator.InspectAssembly.cs
Compiler/Translator/Utils/Exception.cs
Compiler/Translator/Utils/Roslyn/ChainingAssigmentReplacer.cs
Compiler/Translator/Utils/Roslyn/DeconstructionReplacer.cs
Compiler/Translator/Utils/Roslyn/DiscardReplacer.cs
Compiler/Translator/Utils/Roslyn/IsPatternReplacer.cs
Compiler/Translator/Utils/Roslyn/LocalFunctionReplacer.cs
Compiler/Translator/Utils/Roslyn/ReplacerException.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Compiler/Translator/Utils/Roslyn/SwitchPatternReplacer.cs
Compiler/Translator/Utils/Roslyn/UsingStaticReplacer.cs

Adds exceptions to improve error reporting from Bridge Translator

Improves #3550 and #3557 error reporting

---

Bridge/Bridge/Script.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3500/N3580.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3580] New Script.Return helper method

---

Bridge/Bridge.csproj
Bridge/shared/System/Resources/IResourceReader.cs
Bridge/shared/System/Resources/MissingManifestResourceException.cs
Bridge/shared/System/Resources/MissingSatelliteAssemblyException.cs
Bridge/shared/System/Resources/NeutralResourcesLanguageAttribute.cs
Bridge/shared/System/Resources/ResourceFallbackManager.cs
Bridge/shared/System/Resources/ResourceTypeCode.cs
Bridge/shared/System/Resources/RuntimeResourceSet.cs
Bridge/shared/System/Resources/SatelliteContractVersionAttribute.cs
Bridge/shared/System/Resources/UltimateResourceFallbackLocation.cs

Add missing System.Resources classes

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Tests/Runner/Batch1/bridge.js

[3617] Task.Start raises exception in IE and Edge.

---

Compiler/Translator/Utils/Roslyn/LocalFunctionReplacer.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3600/N3625.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3625] Emit order of Nested Functions

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Compiler/Translator/Emitter/Blocks/InlineArgumentsBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3600/N3612.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3612] Error on boxing of nullable enums

---

.build/specs/Bridge.Min.nuspec
Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/Translator/Translator.ProjectReader.cs
Compiler/Translator/packages.config
Compiler/TranslatorTests/Bridge.Translator.Tests.csproj
Compiler/TranslatorTests/packages.config

[3632] Fixes linux building issue related to new CSProj format support.

---

Compiler/Translator/Emitter/Blocks/MemberReferenceBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3600/N3658.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3658] Issue when copy a nullable struct value to a new struct variable

---

Bridge/Resources/.generated/System/Collections/Generic/list.js
Bridge/Resources/.generated/System/Collections/Generic/stack.js
Bridge/Resources/.generated/System/Collections/ObjectModel/Collection.js
Bridge/Resources/.generated/System/ComponentModel/defaultValueAttribute.js
Bridge/Resources/.generated/System/DateTimeOffset.js
Bridge/Resources/.generated/System/Diagnostics/Debug.js
Bridge/Resources/.generated/System/Globalization/Calendar.js
Bridge/Resources/.generated/System/IO/BinaryReader.js
Bridge/Resources/.generated/System/IO/BufferedStream.js
Bridge/Resources/.generated/System/IO/MemoryStream.js
Bridge/Resources/.generated/System/IO/ReadLinesIterator.js
Bridge/Resources/.generated/System/IO/Stream.js
Bridge/Resources/.generated/System/IO/StreamReader.js
Bridge/Resources/.generated/System/IO/StreamWriter.js
Bridge/Resources/.generated/System/SR.js
Bridge/Resources/.generated/System/Text/UTF7Encoding.js
Bridge/Resources/.generated/System/Version/versionResult.js
Bridge/Resources/.generated/bridge.js
Compiler/Translator/Emitter/Blocks/Block.cs
Compiler/Translator/Emitter/Blocks/TryCatchBlock.cs
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/Test.BridgeIssues.N084.js
Compiler/TranslatorTests/TestProjects/16/Bridge/reference/bridge.report.log
Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
Tests/Runner/Batch1/Bridge.Test/main.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/code.js
Tests/Runner/ClientTestHelper/code.js

[3445] JavaScript try/catch/finally block formatting

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Array.js
Tests/Runner/Batch1/bridge.js

Fix for https://forums.bridge.net/forum/community/help/5583-regression-issue-16-8-2-to-17-2-0

[3696] Fix for System.Array ambiguous reference from System.Array.type() js

---

Compiler/Translator/Utils/Roslyn/ChainingAssigmentReplacer.cs
Compiler/Translator/Utils/Roslyn/DeconstructionReplacer.cs
Compiler/Translator/Utils/Roslyn/DiscardReplacer.cs
Compiler/Translator/Utils/Roslyn/ICSharpReplacer.cs
Compiler/Translator/Utils/Roslyn/IsPatternReplacer.cs
Compiler/Translator/Utils/Roslyn/LocalFunctionReplacer.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Compiler/Translator/Utils/Roslyn/SwitchPatternReplacer.cs
Compiler/Translator/Utils/Roslyn/SyntaxHelper.cs
Compiler/Translator/Utils/Roslyn/UsingStaticReplacer.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2400/N2499.cs
Tests/Batch3/BridgeIssues/3700/N3742.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3742] Invalid token generated for template function

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Bridge/Resources/linq.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3600/N3672.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3672] Comparer<string>.Default not using System.String.compare

---

Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.Locals.cs
Tests/Runner/Batch3/code.js

[3745] Inccorect translation

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Reflection.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3700/N3746.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3746] Wrong assembly name in arrays

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3700/N3738.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3738] Casting an expression with null-condition operator (?) fails

---

Compiler/Translator/Emitter/Blocks/ForBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3700/N3743.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3743] for loop multiple variables intialization is broken async methods.

---

Bridge/System/Delegate.cs

[3531] Add method `GetInvocationList` in `Delegate` class

---

Compiler/Translator/Emitter/Blocks/ConversionBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3700/N3759.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3759] Needless boxing when using extension methods

---

Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3700/N3762.cs

[3762] Invalid JS generated in very specific case

---

Compiler/Translator/Emitter/Emitter.Properties.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs

Guys.
You load same references 2 times:
1st with roslyn
2nd with nrefactory
Please choose one of this libries in future. Make some tests or something please.

Issue3805 Cache references for next compilation

---

Bridge/Resources/.generated/bridge.js
Compiler/Translator/Utils/Roslyn/IsPatternReplacer.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3800/N3823.cs
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3823] Checking if an object is decimal always results as true

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Reflection.js
Bridge/System/Type.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2500/N2522.cs
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2522] Implement Type.IsPrimitive

---

Bridge/Resources/.generated/bridge.js
Compiler/Translator/Inspector/Validator.cs
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js

[3815] Only one ModuleDependencyAttribute is used

---

Bridge/Resources/.generated/bridge.js
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3800/N3820.cs
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3820] Bug at using Ref Returns

---

Bridge/Resources/.generated/System/Collections/Generic/enumerableHelpers.js
Bridge/Resources/.generated/System/Collections/Generic/stack.js
Bridge/Resources/.generated/bridge.js
Bridge/Resources/Array.js
Bridge/System/Array.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3800/N3830.cs
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3830] Array.CreateInstance is not safe

---

Bridge/Resources/.generated/bridge.js
Compiler/Translator/Emitter/Blocks/AsyncBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3800/N3836.cs
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3836] Issue with async inline delegates ($taskResult1 is not defined)

---

Bridge/Resources/.generated/bridge.js
Compiler/Translator/Emitter/Emitter.OutputModule.cs
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js

[3848] Issue creating generic type inside of manually loaded module

---

Bridge/Resources/.generated/bridge.js
Compiler/Translator/Emitter/Blocks/EmitBlock.cs
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js

[3858] Assembly attributes is not adding when use module

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Reflection.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3800/N3865.cs
Tests/Runner/Batch1/bridge.console.js
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3865] Array of Array haven't assembly

---

Compiler/Translator/Bridge.Translator.csproj
Compiler/Translator/Emitter/Emitter.Properties.cs
Compiler/Translator/Translator/ReferenceInfo.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs

Fixes #3824 
- Cache references by service class with equals and hashcode

[3824] Cache references

---

Compiler/Translator/Utils/Roslyn/LocalFunctionReplacer.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3800/N3871.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3871] Local async function failing

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/ClientWebSocket.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3800/N3821.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3821] task suspend at websocket

---

Compiler/Translator/Emitter/Blocks/UnaryOperatorBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3800/N3898.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3898] Negative zero literal not supported

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Math.js
Bridge/System/Math.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3800/N3899.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3899] Math.IEEERemainder gives wrong results

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Integer.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3900/N3900.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3900] Math.Sign can not handle infinity values.

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Long.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3800/N3883.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3883] Trying to cast input.files[0].size to long causes a crash

---

Compiler/Translator/Emitter/Blocks/ObjectCreateBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3800/N3886.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3886] Object initializers not working with property templates

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Nullable.js
Compiler/Translator/Emitter/Blocks/AssignmentBlock.cs
Compiler/Translator/Emitter/Blocks/BinaryOperatorBlock.cs
Tests/Batch1/NullableTests.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3900/N3903.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3903] The ^ operator for bool values returns weird result

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Class.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3900/N3907.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3907] Method invocation via an interface can fail for ToString

---

Bridge/Resources/.generated/System/Collections/Generic/Dictionary.js
Bridge/Resources/.generated/System/Collections/Generic/SortedList.js
Bridge/Resources/.generated/System/Collections/Generic/enumerableHelpers.js
Bridge/Resources/.generated/System/Collections/Generic/list.js
Bridge/Resources/.generated/System/Collections/Generic/queue.js
Bridge/Resources/.generated/System/Collections/Generic/stack.js
Bridge/Resources/.generated/bridge.js
Bridge/Resources/Array.js
Compiler/Translator/Emitter/Blocks/InlineArgumentsBlock.cs
Tests/Runner/Batch1/bridge.js

[3930] Generic array allocation unreasonably slow

---

Compiler/Translator/Emitter/Emitter.OutputModule.cs

[3933] Use string index instead of object property to declare modules

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Convert.js
Tests/Batch1/Convert/ConvertTestBase.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3900/N3934.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3934] Convert.ToSingle does not respect format provider

---

Bridge/Resources/.generated/System/Collections/Generic/SortedList.js
Bridge/Resources/.generated/System/Collections/hashHelpers.js
Bridge/Resources/.generated/System/IO/BinaryWriter.js
Bridge/Resources/.generated/System/IO/Stream.js
Bridge/Resources/.generated/System/IO/StreamReader.js
Bridge/Resources/.generated/System/IO/TextWriter.js
Bridge/Resources/.generated/System/Reflection/Module.js
Bridge/Resources/.generated/System/version.js
Bridge/Resources/.generated/bridge.js
Compiler/Translator/Emitter/Blocks/FieldBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3900/N3943.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3943] incorrect initialization of static member with const

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Tests/Runner/Batch1/bridge.js

[3932] Wrong Generic generation with modules

---

Compiler/Translator/Emitter/Emitter.Properties.cs
Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs

Fixes #3936
Removed all my "optimization" code

Issue3936 Fix Memory Leaks

---

Bridge/Resources/.generated/System/IO/FileStream.js
Bridge/Resources/.generated/System/IO/StreamReader.js
Bridge/Resources/.generated/bridge.js
Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3900/N3951.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3951] await on an already completed Task can abort async method

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Decimal.js
Bridge/Resources/Integer.js
Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.Write.cs
Tests/Batch1/Convert/ConvertTestBase.cs
Tests/Batch1/DecimalMathTests.cs
Tests/Batch1/MathTests.cs
Tests/Batch1/SimpleTypes/DecimalTests.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/0900/N968.cs
Tests/Batch3/BridgeIssues/2600/N2644.cs
Tests/Batch3/BridgeIssues/3800/N3887.cs
Tests/ClientTestHelper/Internal/NumberHelper.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/code.js
Tests/Runner/ClientTestHelper/code.js

[3887] Incorrect to string value for a decimal

---

Bridge/Resources/.generated/System/IO/FileStream.js
Bridge/Resources/.generated/System/IO/StreamReader.js
Bridge/Resources/.generated/bridge.js
Bridge/Resources/Task.js
Compiler/Contract/Constants/JS.cs
Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3963] Implementation of await should not call ContinueWith

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/String.js
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3900/N3964.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3964] string.IndexOfAny is implemented incorrectly

---

Bridge/System/Linq/Enumerable.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3900/N3977.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3977] Enumearable.join() does not reference outer table

---

Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.Locals.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/3900/N3994.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[3994] Optional Parameters of Enum Types are not generated correctly

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Reflection.js
Bridge/System/Reflection/MemberInfo.cs
Bridge/System/Reflection/MethodInfo.cs
Bridge/System/Type.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/2800/N2894.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[2894] Support MakeGenericMethod.

---

Bridge/Resources/.generated/System/IO/FileStream.js
Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Compiler/Translator/Emitter/Blocks/ObjectCreateBlock.cs
Tests/Batch1/DelegateTests.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/1500/N1563.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js
Tests/Runner/Batch4/code.js

[1563] Delegate - Additive operators do not work

---

Compiler/Translator/Emitter/Emitter.Helpers.cs
Tests/Batch3/Batch3.csproj
Tests/Batch3/BridgeIssues/4000/N4015.cs
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[4015] Class with 'extern' indexer is translated into invalid JS

---

Bridge/Resources/.generated/bridge.js
Bridge/Resources/Core.js
Tests/Batch3/BridgeIssues/1500/N1563.cs
Tests/Runner/Batch1/bridge.js
Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
Tests/Runner/Batch3/code.js

[1563] Additional fix for remove operator
