bridgedotnet/Bridge

- Bridge/System/String.cs
This won't compile with the mono compiler, because the
whitespace in front doesn't get omitted with the mono
compiler.
Also, the recompiled version of bridge.js and bridge.min.js is quite different: https://gist.github.com/txdv/9666bf169561a866846c on mono, but this has no code change, only comment change, so the generated output on windows should be the same.
> Fix wrong xml param name.

- Html5/Location.cs
Relates to #264.
I am relying on the [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/Location).
> [FIX] Location.Hash and other fields are read only, but they shouldn't be (except Origin).

- Bridge/System/Math.cs
Change constants from const to static readonly and add [Name(false)] attribute
> Issue #410 Math.X constants can be optimized away by compiler

- Compiler/Contract/Helpers.cs
- Compiler/Contract/IAssemblyInfo.cs
- Compiler/Translator/Utils/AssemblyInfo.cs
This is a small feature I added to Bridge to globally control the "IgnoreCast" setting. My project is not only targeting JavaScript and therefore I want to keep my core classes mostly clean from third party code (special attributes etc). 
I don't want to spoil my types with additional "IgnoreCast" attributes to control the setting I thought it would be nice to have it globally in the bridge.json.
> Global ignore cast

- Bridge/System/Globalization/CultureNotFoundException.cs
Hi, this PR is a small fix for `CultureNotFoundException` which currently is transformed to `ArgumentOutOfRangeException` by mistake.
#896
> Fix for CultureNotFoundException templates

- Bridge/Resources/Decimal.js
Hi, this PR contains a fix for the regular expression that is used for validation of Decimal value provided in a string (see more information in Issue #968)
> Format validation in Decimal constructor was corrected.

- Compiler/Translator/Emitter/Blocks/ConstructorBlock.cs
- Tests/Batch1/Batch1.csproj
- Tests/Batch1/BridgeIssues/1000/N1024.cs
- Tests/Runner/Batch1/code.js
- Tests/Runner/Batch1/test.js
Addresses #1024 .
https://github.com/bridgedotnet/Bridge/issues/1024
Optional parameters should be initialized before base constructor invocation
> Issue1024 Default parameter value is not being set on the base class

- Html5/Node/Element.cs
> [#1062] Bridge.Html5.Element properties ScrollLeft and ScrollTop are readonly

- Html5/Bridge.Html5.csproj
- Html5/Events/CloseEvent.cs
- Html5/Events/MessageEvent.cs
- Html5/WebSocket.cs
Fixes #776 .
- Implement WebSocket interface as-is in the HTML5.
- Implement related events, such as MessageEvent and CloseEvent.
Note: Though #776 is related to #780, it won't be easy to implement .NET ClientWebSocket, as it goes somewhat apart from HTML5 WebSocket (I'm researching this question now).
> [#776] WebSocket API.

- Html5/Location.cs
Fixes #1088.
- Fix JS names for Window.Location.HostName and Window.Location.PathName.
> [#1088] Some members of Window.Location are translated incorrectly.

- Tests/Batch1/Batch1.csproj
- Tests/Batch1/packages.config
- Tests/Runner/Batch1/bridge.collections.js
Implements #1138 .
This is related to the changes needed in order to Bridge.Collections to work with Bridge 1.12.0+ in issue bridgedotnet/Frameworks#41.
The changes are not backwards compatible so Bridge.Collections version was moved to 1.2.0 (was 1.1.0) and this change reflected in both NuGet package reference and generated `bridge.collections.js` file.
All changes affected only the `Batch1` test project. The other projects were unaffected by this particular update.
> I1138 Update Bridge.Collections to 1.2.0

- Compiler/Translator/Properties/AssemblyInfo.cs
- Compiler/Translator/Translator/Translator.cs
Addresses #1055.
`bridge.log` will contain product info as following
```
Bridge.Compiler version 1.12.0
[Bridge Framework, version 1.12.0]
Copyright 2008-2016 Object.NET, Inc.
```
> Issue1055 Add Builder/Compiler version in a log

- Compiler/Translator/Translator/Translator.cs
> [1195] Specify namespace for `Exception` in catch.

- Html5/CSS/CSSStyleSheet.cs
- Html5/Document.cs
- Html5/File/Blob.cs
- Html5/Interfaces/CanvasRenderingContext2D.cs
- Html5/Interfaces/ImageData.cs
- Html5/Performance.cs
- Html5/TypedArray/ArrayBuffer.cs
- Html5/TypedArray/DataView.cs
- Html5/TypedArray/Float32Array.cs
- Html5/TypedArray/Float64Array.cs
- Html5/TypedArray/Int16Array.cs
- Html5/TypedArray/Int32Array.cs
- Html5/TypedArray/Int8Array.cs
- Html5/TypedArray/Prototype.cs
- Html5/TypedArray/Uint16Array.cs
- Html5/TypedArray/Uint32Array.cs
- Html5/TypedArray/Uint8Array.cs
- Html5/TypedArray/Uint8ClampedArray.cs
- Html5/WebSocket.cs
- Html5/Window.cs
Fixes #1190 .
- Changed erratic fields' ulong type to uint.
Unit tests are to be done yet. To test the issue I used this code:
```
public class App
{
[Ready]
public static void Main()
{
// Test Case #1
var fileInput = new InputElement
{
Type = InputType.File,
OnChange = (ev) => 
{
File file = ev.CurrentTarget.Files[0];
long size = (long)file.Size; // this throws a JavaScript error at runtime
}
};
Document.Body.AppendChild(fileInput);
// Test Case #2
ImageData imageData = new ImageData(100, 100);
long height = (long)imageData.Height; // this throws a JavaScript error at runtime
long width = (long)imageData.Width; // this throws a JavaScript error at runtime
// Test Case #3
var webSocket = new WebSocket("ws://echo.websocket.org");
var bufferedAmount = …
```
> [FIX] [#1190] Changed erratic fields' ulong type to uint

- Compiler/Contract/IAssemblyInfo.cs
- Compiler/Translator/Translator/TranslatorProcessor.cs
- Tests/Batch1/Bridge/bridge.Debug.json
- Tests/Batch1/Bridge/bridge.Release.json
- Tests/Batch2/Bridge/bridge.json
- Transpiled/Bridge/bridge.json
Addresses #1237 .
Logging section option names to be:
```
"logging": {
"level": "Info",
"timeStamps": true,
"maxSize": 1048576,
"folder": "Bridge/Logs",
"fileName" : "myBridge.log"
}
```
> Rename logging settings

- Bridge/Resources/Core.js
Fixes #1264
- Core.js behavior when fields are detected
> Make stock object's GetHashCode() repeatable for classes with fields

- Compiler/Build/GenerateScript.cs
- Compiler/Builder/Program.cs
- Compiler/Translator/Translator/TranslatorProcessor.cs
- Compiler/Translator/Utils/BridgeOptions.cs
- Compiler/TranslatorTests/TranslatorRunner.cs
Fixes #1284 .
- setting default name separately for Console and Task - `BridgeOptions.DefaultFileName`
Task: `Path.GetFileNameWithoutExtension(this.Assembly.ItemSpec)`
Console: `Path.GetFileName(bridgeOptions.OutputLocation)`
> Issue1284 "outputBy" configuration option results in an empty filename

- Bridge/System/String.cs
- Tests/Batch1/Batch1.csproj
- Tests/Batch1/BridgeIssues/1300/N1316.cs
- Tests/Runner/Batch1/code.js
- Tests/Runner/Batch1/test.js
Fixes #1316.
Adds missing `string.Concat` overrides
- `Concat(IEnumerable<String>)`
- `Concat<T>(IEnumerable<T>)`
- `Concat(Object)`
> Issue1316 String (+) operator doesn't work on empty string (s)

- Html5/Interfaces/CanvasRenderingContext2D.cs
- Renamed CanvasRenderingContext2D.SetTransfrom to SetTransform.
- Removed duplicate generic arguments in all overloads of CanvasRenderingContext2D.DrawImage.
**UPD**: Addresses #1368
> Mispelling in CanvasRenderingContext2D.SetTransform

- Compiler/Builder/Program.cs
Closes #1132
- Change the signature of `GetBridgeOptionsFromCommandLine` to `(ref string[], ILogger)` so that we may output the modified args instead of whatever was passed in.
- Only call `ShowHelp` when `GetBridgeOptionsFromCommandLine` returns `null`
- `Bridge.Builder.exe` will now default to a `csproj` in the target folder (either with the `-f` flag, or the cwd) if a single `csproj` is found
I will need help with this:
> (it would have to support reading *.csproj.user files for current configuration, or maybe reading environment variables if VS makes them available on events/tasks calls).
> Bridge Builder: Default to a single csproj if found

- Bridge/Bridge.csproj
- Bridge/Resources/ArraySegment.js
- Bridge/Resources/Bridge.jsb
- Bridge/Resources/ClientWebSocket.js
- Bridge/Resources/Uri.js
- Bridge/System/ArraySegment.cs
- Bridge/System/Net/WebSockets/ClientWebSocket.cs
- Bridge/System/Net/WebSockets/ClientWebSocketOptions.cs
- Bridge/System/Net/WebSockets/WebSocketCloseStatus.cs
- Bridge/System/Net/WebSockets/WebSocketMessageType.cs
- Bridge/System/Net/WebSockets/WebSocketReceiveResult.cs
- Bridge/System/Net/WebSockets/WebSocketState.cs
- Bridge/System/Uri.cs
Fixes #780.
- Implement wrapper for Javascript that behaves like .NET ClientWebSocket.
Note: Some methods with -Async suffix return Task that actually doesn't represent task state (due to Javascript limitations).
> [#780] Consider support/handling of System.Net.

- Compiler/Build/Bridge.Build.csproj
- Compiler/Build/GenerateScript.cs
- Compiler/Build/VSLoggerWriter.cs
- Compiler/Translator/Emitter/Blocks/ConstructorBlock.Events.cs
- Compiler/Translator/Emitter/Blocks/ConstructorBlock.cs
Fixes #1406
- implement VS logger for errors and warnings
- auto-run methods ([Ready] and #1303 methods) to show VS warnings if the class or the method is generic
> Issue1406 Warning for generic auto-run methods

- Compiler/Translator/Inspector/Inspector.Visitor.cs
- Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.js
- Compiler/TranslatorTests/TestProjects/02/BridgeIssues/N1424.cs
- Compiler/TranslatorTests/TestProjects/02/test.csproj
- Compiler/TranslatorTests/TestProjects/16/Bridge/reference/test.bridgeIssues.n1424.js
- Compiler/TranslatorTests/TestProjects/16/BridgeIssues/1500/N1424.cs
- Compiler/TranslatorTests/TestProjects/16/test.csproj
Fixes #1424
- If property has `[FieldPropery]` attribute but has a getter/setter implementation then the Compiler throws error like `[Property TestApp.A.K] is marked with [FieldProperty] attribute but implements getter and setter. To fix the problem either remove [FieldProperty] (swith off bridge.json option `autoPropertyToField`) or add [External]/[Template] attributes`;
- The same thing when bridge.json option `autoPropertyToField` turned on.
> Issue1424 Properties with setter or getter implementation and [FieldProperty] should not compile

- Compiler/Translator/Translator/TranslatorProcessor.cs
There was an unnecessary assignment statements in TranslatorProcessor.cs. I've also moved moved some else blocks to begin on a separate line in order to keep the formatting consistent with the rest of the code.
> removed redundant assignments and improved formatting

- Compiler/Translator/Inspector/Inspector.Visitor.cs
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/0700/N706.cs
- Tests/Runner/Batch3/code.js
- Tests/Runner/Batch3/test.js
#706
Field initializer implemented in #1435.
This PR fixes a case when `[FieldProperty]` used.
> [#706] Support FieldProperty with initializer

- Compiler/Contract/BridgeType.cs
- Compiler/Contract/ITranslator.cs
- Compiler/Contract/ITypeInfo.cs
- Compiler/Translator/Emitter/Blocks/EmitBlock.cs
- Compiler/Translator/Emitter/Emitter.cs
- Compiler/Translator/Translator/Translator.ProjectReader.cs
- Compiler/Translator/Translator/Translator.Properties.cs
- Compiler/Translator/Translator/Translator.cs
- Compiler/Translator/Utils/CaptureAnalyzer.cs
- Compiler/Translator/Utils/TypeInfo.cs
> [1725] Use `Translator.DefaultNamespace` if no namespace provided

- Html5/Document.cs
Modify Document.Body to return an HTMLBodyElement object. Issue #1516.
Modify Document.DocumentElement to return an HTMLHtmlElement object. Issue #1771.
> Fixes Document.Body and Document.DocumentElement return types

- Tests/Batch1/Batch1.csproj
- Tests/Batch1/Constants.cs
- Tests/Batch1/FormattableStringTests.cs
- Tests/Runner/Batch1/code.js
- Tests/Runner/Batch1/test.js
Fixes #1622 
`FormattableString` was added as part of Reflection support.
This PR is to add tests.
> [1622] `FormattableString` tests

- Tests/Batch1/Batch1.csproj
- Tests/Batch1/Exceptions/AmbiguousMatchExceptionTests.cs
- Tests/Runner/Batch1/code.js
- Tests/Runner/Batch1/test.js
Fixes #1621
`AmbiguousMatchException` was added as part of Reflection support.
This PR is to add tests.
> [1621] AmbiguousMatchException tests

- Html5/Performance.cs
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/1500/N1509.cs
- Tests/Runner/Batch3/code.js
- Tests/Runner/Batch3/test.js
Fixes #1509
- `Performance.Now()` returns `double`
- Client test
> [1509] Performance.Now should return double

- Html5/Events/Event.cs
- Html5/Events/ProgressEvent.cs
Fixes #1816
- Option1 from https://github.com/bridgedotnet/Bridge/issues/1816#issuecomment-251075624
- Event's `CurrentTarget` and `Target` to be of less specific type `EventTarget` (instead of `HtmlElement`);
- `ProgressEvent<T>` to inherit properties of `ProgressEvent` and override Event's `CurrentTarget` and `Target`.
> [1816] Event's `CurrentTarget` and `Target` to be of less specific type

- .build/files/Bridge.Min.targets
Fixes #1961
- Bridge script task (Bridge.Min.targets) to run on `PrepareForRun` instead of `AfterBuild`
- Added info messages that are shown in Build output window on the script task starts and finishes
```
------ BridgeGenerateScript task done: Project: $(MSBuildProjectName), Configuration: $(Configuration) $(Platform)
```
> [1961]  Project post build event task is called before Bridge GenerateScript task

- Compiler/Contract/Config/ConfigHelper.cs
- Compiler/TranslatorTests/Bridge.Translator.Tests.csproj
- Compiler/TranslatorTests/ContractTests/ConfigHelperTests.cs
See #1960
- Do not replace trailing double '\\' or '//' in paths in case for server apps like
For, example,  **\\root\folder\**
Convertion result for  **\\root/folder/**
- before fix  **\root\folder\**
- after fix  **\\root\folder\**
Fixes PR #1990
> [1990] Fix path conversion

- .travis.yml
```
The line below starts failing in travis-build version: 5ddd724fb
Issue logged - https://github.com/travis-ci/travis-ci/issues/6854
mono .nuget/nuget.exe
```
> Fix Travis build issue (in travis-build version: 5ddd724fb)

- Compiler/Translator/Utils/AssemblyInfo.cs
- Compiler/TranslatorTests/TestProjects/15/Bridge/bridge.json
Fixes #2074
-  Set `outputBy: "Project"` if fileName being used
> [2074] "fileName" option in bridge.json requires outputBy Project

- Bridge/Bridge/Any.cs
Add implicit operators from `Any` to` Union` (and back) to make migration to `Union` (as` Any` is now obsolete) easier to do one piece at a time. Addresses #2116.
I would like to start updating my projects and libraries to move away from `Any` to `Union` but it would be easier if I could update one project at a time and still have it build, which I could if `Any` and `Union` could be used interchangeably.
> [2116] Add implicit operators from Any to Union (and back)

- Compiler/Build/GenerateScript.cs
- Compiler/Translator/Translator/Translator.cs
- Compiler/Translator/Translator/TranslatorProcessor.cs
- Compiler/TranslatorTests/OutputTest.cs
- Compiler/TranslatorTests/TestProjects/02/Bridge/reference/TestProject.I2096.js
- Compiler/TranslatorTests/TestProjects/02/test.csproj
Fixes #2096
The bug was it considered a file name as a file name with extention and were removing last segment.
Reproduced when building with Bridge Task (not Bridge.Builder.exe console).
> [2096] Output file name gets last segment cut when outputBy Project option is used

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/Attribute.js
- Bridge/System/Attribute.cs
- Bridge/System/Reflection/MemberInfo.cs
- Bridge/System/Reflection/ParameterInfo.cs
- Tests/Batch1/Reflection/AttributeTests.cs
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch1/code.js
- Tests/Runner/Batch1/test.js
- Tests/Runner/Batch4/code.js
Fixes #2043  .
- Add checks on `null` arguments for `Attributes.GetCustomAttributes()` methods
> [2043] Implement Attribute.GetCustomAttributes: checks on null method arguments

- Compiler/Translator/Emitter/Blocks/FieldBlock.cs
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/2100/N2137.cs
- Tests/Runner/Batch1/code.js
- Tests/Runner/Batch1/test.js
- Tests/Runner/Batch2/test.js
- Tests/Runner/Batch3/code.js
- Tests/Runner/Batch3/test.js
- Tests/Runner/Batch4/code.js
- Tests/Runner/Batch4/test.js
> [2137] CSharp6 Getter-only auto-properties cause too many closing braces emitted (not const in right-hand)

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/Math.js
- Bridge/System/Math.cs
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/1500/N1566.cs
- Tests/Batch4/MathTests.cs
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch1/code.js
- Tests/Runner/Batch3/code.js
- Tests/Runner/Batch3/test.js
- Tests/Runner/Batch4/code.js
- Tests/Runner/Batch4/test.js
See #1566.
This PR is to merge changes introduced by @Zaid-Ajaj PR #2132, correct it a bit and add client tests.
- Missing [MSDN Math.Log10 Method (Double)](https://msdn.microsoft.com/en-us/library/system.math.log10%28v=vs.110%29.aspx)
- Compatible with .Net [tests](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/System/Math.cs#L251)
- Missing [MSDN Math.Log Method (Double, Double)](https://msdn.microsoft.com/en-us/library/system.math.log10%28v=vs.110%29.aspx)
- Compatible with the .Net [implementation](https://referencesource.microsoft.com/#mscorlib/system/math.cs,506)
- Compatible with .Net [tests](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/System/Math.cs#L239)
- Fix …
> [1566] [Zaid-Ajaj] Math.Log fixes

- Bridge/System/DateTime.cs
- Tests/Batch1/Batch1.csproj
- Tests/Batch1/SimpleTypes/DateTimeTests.cs
- Tests/Runner/Batch1/code.js
- Tests/Runner/Batch1/test.js
Fixes #2149.
This PR is to merge changes introduced by @Zaid-Ajaj PR #2150, correct it a bit to support culture locales and add client tests.
> [2149] Support DateTime's ToShortDateString() and ToShortTimeString()

- Bridge/System/Math.cs
- Tests/Batch1/MathTests.cs
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/2300/N2399.cs
- Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
- Tests/Runner/Batch1/code.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
Fixes #2399
-  Math.Sqrt(decimal d) is removed because it is not presented in .NET API
> [2399] Math.Sqrt and unsigned integers don't work.

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/Json.js
- Tests/Batch1/Serialization/SerializationTests.cs
- Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch1/code.js
- Tests/Runner/Batch2/Bridge.Test/bridge.clienttest.batch2.runner.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch4/Bridge.Test/bridge.clienttest.batch4.runner.js
- Tests/Runner/Batch4/code.js
Addresses #2427 Support JsonSettings for Bridge.Json (a part of #2418 Bridge.Json serialization and deserialization ) - https://github.com/bridgedotnet/Bridge/issues/2418#issuecomment-284032029
- Assembly name is included to serialized type name
> [2418] Add assembly name to `$type` field

- Compiler/Contract/Config/ResourceConfig.cs
- Compiler/Translator/Translator/Translator.Resources.cs
- Compiler/TranslatorTests/TestProjects/18/Bridge/bridge.json
- Compiler/TranslatorTests/TestProjects/18/Bridge/reference/resources/issue2429_Bom.css
- Compiler/TranslatorTests/TestProjects/18/Bridge/reference/resources/issue2429_NoBom.css
- Compiler/TranslatorTests/TestProjects/18/Bridge/res/style2429_1.css
- Compiler/TranslatorTests/TestProjects/18/Bridge/res/style2429_2.css
- Compiler/TranslatorTests/TestProjects/18/test.csproj
Fixes #2429 
* Remove BOM when combining resources
* Config option for resource items with files **resources.removeBom** (default true):
```js
"resources": [
{
// new option
"removeBom": false|true (true by default)
"name": "combined.css",
"files": [ "style1WithBom.css",  "style2WithBom2.css" ]
}
]
```
> [2429] Bundled CSS files contain byte-order-marks within the combined output file

- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/2400/N2467.cs
- Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
Unit test for #2467 
The fix was commited in https://github.com/bridgedotnet/Bridge/pull/2464
> [2467] Property auto-intialiser in struct doesn't work (unit test)

- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/2400/N2486.cs
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
> [2486] Tests for generic interface where generic type is array caused runtime error

- Compiler/Translator/Utils/AssemblyInfo.cs
- Compiler/TranslatorTests/CompilerTests/AssemblyInfoTests.cs
- Compiler/TranslatorTests/TestProjects/03/Bridge/bridge.json
- Compiler/TranslatorTests/TestProjects/10/Bridge/bridge.json
- Compiler/TranslatorTests/TestProjects/11/Bridge/bridge.json
- Compiler/TranslatorTests/TestProjects/18/Bridge/bridge.json
- Compiler/TranslatorTests/TestProjects/19/Bridge/bridge.json
> [2536] Setting outputBy to be Project by default (before - Namespace)

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/.generated/system/environment.js
- Bridge/Resources/Collections/Dictionary.js
- Bridge/System/Environment.cs
- Bridge/bridge.json
- Tests/Batch1/EnvironmentTests.cs
- Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch1/code.js
Addresses #2224, #2553
This is not an exact copy of .Net behavior:
- Enrironment variables are stored in **Environment** static field. I.e. it does not contain OS environment variables. However the API allows adding, storing, handling (for example, **public static string ExpandEnvironmentVariables(string name)**) and removing in .Net-like way;
- Things related to **command line** - `location.pathname` and `location.search`;
- **CurrentDirectory** - `location.pathname`
- **ExitCode** is stored as a property, allows setting by the property and by `Exit(int exitCode)`;
- **Is64BitOperatingSystem** tries to get it analizing `(n.userAgent.indexOf("WOW64") != -1 || n.userAgent.indexOf("Win64") != -1))`
- **ProcessorCount** - `navigator.hardwareConcurrency`
- **StackTrace** - an apporach like …
> [2224] Support for Environment class

- .build/files/Bridge.Min.targets
- .build/specs/Bridge.Min.nuspec
- Compiler/Build/GenerateScript.cs
- Compiler/TranslatorTests/TestProjects/02/test.csproj
Addresses #2668:
To prevent Visual Studio from caching task assembly when upgrading from 15.7 -> 16.0:
* Visual Studio task renamed **GenerateScript** -> **BridgeCompilerTask**
* nuspec task assembly renamed **Bridge.Builder.dll** -> **Bridge.Builder.v16.dll**
> 16.0 upgrade experience: VS task assembly caching

- Html5/Document.cs
- Html5/DocumentFragment.cs
- Html5/DocumentInstance.cs
- Html5/Elements/Element.cs
Fixes #2660. 
Changes **QuerySelector** return type to **Element**:
* https://developer.mozilla.org/en/docs/Web/API/Document/querySelector
* https://developer.mozilla.org/en/docs/Web/API/Element/querySelector  
> Returns the first Element within the document that matches the specified selector, or group of selectors.
**QuerySelectorAll** to **NodeList**
* https://developer.mozilla.org/en/docs/Web/API/Document/querySelectorAll
> Returns a list of the elements within the document (using depth-first pre-order traversal of the document's nodes) that match the specified group of selectors. The object returned is a NodeList.
**GetElementsByName** to **NodeList**:
* https://developer.mozilla.org/en/docs/Web/API/Document/getElementsByName
> Returns a NodeList collection with a given name in the …
> [2660] Element.QuerySelector returns a Node rather than an Element

- Compiler/Translator/Utils/LoopVariablesAnalyzer.cs
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/2700/N2705.cs
- Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
> [2705] Catch clause without variable inside a loop with delegate raises an exception

- Compiler/Build/GenerateScript.cs
- Compiler/Build/VSLoggerWriter.cs
- Compiler/Builder/Program.cs
Addresses log issue specified [here](http://https//forums.bridge.net/forum/bridge-net-pro/bugs/4368-closed-2816-16-0-compile-error-with-combinescripts-and-extract-bridge-console-js?p=4382#post4382) by @ProductiveRage:
* Info and Trace messages into VS output window (before only into log file);
* Error level message goes into log file as well (before only into VS error/output window)
> Visual Studio logger enhancement

- Compiler/Translator/Constants/Messages.cs
- Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.Locals.cs
- Compiler/Translator/Emitter/Blocks/SwitchBlock.cs
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/2800/N2847.cs
- Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
> [2847] Declaring a variable with same name in multiple switch statements causes error

- .build/ci/Gruntfile.js
Windows XP is not supported by Sauce Labs anymore - https://wiki.saucelabs.com/pages/viewpage.action?pageId=70074721
> Cross browser test configuration: Win XP -> Win 8.1

- .build/common/CommonAssemblyInfo.cs
- .build/specs/Bridge.Compiler.nuspec
- .build/specs/Bridge.Html5.nuspec
- .build/specs/Bridge.Min.nuspec
- .build/specs/Bridge.nuspec
Bridge .nuspec dependency for other bridge NuGet packages was not
properly changed to 16.4.0. This commit sets them up to the right
version.
> Pulls NuSpec files' dependency version up to 16.4.0.

- Compiler/Translator/Translator/Translator.Resources.cs
- Compiler/Translator/Utils/ByteSizeHelper.cs
This makes numbers output to the report file to be dumped with
culture-independent .ToString() calls.
Fixes #3227.
- Sets up output of report files generated by Bridge.Translator to use culture-invariant number formatting
- Keeps methods contracts intact so that other code calling them don't get affected by the changes
- Will only use culture invariant output when explicitly specified, defaults to the former behavior.
> Fixes Bridge Translator's report file number output.

- .build/files/Bridge.Min.targets
- Compiler/Build/GenerateScript.cs
- Compiler/Build/VSLoggerWriter.cs
- Compiler/Builder/Program.cs
- Compiler/Contract/Bridge.Contract.csproj
- Compiler/Contract/Config/ConfigHelper.cs
- Compiler/Contract/Config/IAssemblyInfo.cs
- Compiler/Contract/Config/StringBoolJsonConverter.cs
- Compiler/Translator/Translator/Translator.Build.cs
- Compiler/Translator/Translator/Translator.Output.cs
- Compiler/Translator/Translator/Translator.ProjectReader.cs
- Compiler/Translator/Translator/TranslatorProcessor.cs
- Compiler/Translator/Utils/AssemblyConfigHelper.cs
- Compiler/Translator/Utils/AssemblyInfo.cs
- Compiler/TranslatorTests/CompilerTests/AssemblyConfigHelperTests.cs
- Compiler/TranslatorTests/CompilerTests/AssemblyInfoJsonConvertersTests.cs
- Compiler/TranslatorTests/CompilerTests/AssemblyInfoTests.cs
- Compiler/TranslatorTests/IntegrationTests/TranslatorRunner.cs
Fixes #3155
New successful rebuild logging has been cleaned up and reduced to the following. 
```
------ Rebuild All started: Project: Demo1, Configuration: Debug Any CPU ------
Demo1 -> c:\users\user\Demo1\bin\Debug\Demo1.dll
Bridge started
To enable further logging use config setting "logging" in bridge.json.
https://github.com/bridgedotnet/Bridge/wiki/global-configuration#logging
Bridge done
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
````
> [3155] Default logging of Bridge compiler is super-verbose

- .build/files/bridge.json
Revisions include:
1. Add `outputFormatting` config
1. Disable .min.js file generation by default
1. Disable **bridge.report.log** file generation
1. Added some docs
1. _See all bridge.json options_ message moved to top
> Revised bridge.json

- .build/files/Bridge.Min.targets
Fixes #3100 .
- Adds 'mono' to the commandline call for bridge in Bridge.Min.Targets if the OS is `Unix`
> [3100] Fixes Bridge.Min.targets *nix compatibility.

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/Date.js
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3200/N3293.cs
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
Fixes #3293 .
- System.DateTime comparison to use System.Int64's compare methods.
> [3293] problems with comparisons with DateTime.MaxValue

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/Core.js
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3300/N3331.cs
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
Fixes #3331.
- Return `undefined` when incorrect property is requested from *NamedNodeMap* object.
> [3331] InvalidCharacterError in Microsoft Edge

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/Enum.js
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3300/N3346.cs
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
> [3346] Enum.TryParse nulls the out parameter if unable to parse

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/Core.js
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3300/N3391.cs
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
> [3391] Using Equals() on the same boxed enum returns false

- Compiler/Contract/BridgeType.cs
- Compiler/Contract/OverloadsCollection.cs
- Compiler/Translator/Emitter/Blocks/FieldBlock.cs
- Compiler/Translator/Emitter/Blocks/VisitorMethodBlock.cs
- Compiler/Translator/Utils/MetadataUtils.cs
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3300/N3388.cs
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
> [3388] Two excplicit implementations of generic interface are indistinguishable

- Compiler/Translator/Emitter/Blocks/ConversionBlock.cs
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3400/N3404.cs
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
> [3404] Extension method for decimal with additional string parameter produces invalid code.

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/Convert.js
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3400/N3415.cs
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
Fixes #3415 .
- Changes the behavior of Convert.js' Convert.ToString() when the passed object has a custom implementation of ToString().
> [3415] Convert.ToString returning type when ToString method is available

- Compiler/Translator/Emitter/Blocks/MemberReferenceBlock.cs
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3400/N3418.cs
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
Fixes #3418.
- Fixes events' templates not parsing `{value}` tokens correctly when no `{this}` token is provided.
- Adds unit tests
> [3418] Template attribute does not work on event if the `{this}` placeholder is missing

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/Collections/Dictionary.js
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3400/N3408.cs
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
Fixes #3408 .
- Changes System.Collections.Generic.Dictionary.getValue() client-side implementation to return an array of values when the dictionary keys are complex.
- Adds unit tests
> [3408] Dictionary<T, _>.Values.CopyTo NotImplemented

- Bridge/System/Collections/Generic/Dictionary.cs
- Bridge/System/Object.cs
- Tests/Batch1/Collections/Generic/IDictionaryTests.cs
- Tests/Batch1/Collections/Generic/IReadOnlyDictionaryTests.cs
- Tests/Batch3/BridgeIssues/2100/N2141.cs
- Tests/Batch3/BridgeIssues/TestBridgeIssues.cs
- Tests/Runner/Batch3/code.js
Fixes #3203.
Branch needed to be rebased and this replaces pr #3487.
> [3203] May object.Keys() method be renamed to something less generic

- .build/files/Bridge.Min.targets
Implements Bridge.Min package's support for building projects following the new, cleaner format introduced by newer netcore technology.
Basically requires the `DisableImplicitFrameworkReferences`, in congruence with pull request #3341, but without all the changes it introduces.
> New CSProj format support

- Compiler/Contract/BridgeType.cs
> [3542] External module reference is not prefixed with the module name

- Compiler/Translator/Utils/Roslyn/LocalFunctionReplacer.cs
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3500/N3558.cs
- Tests/Runner/Batch1/Bridge.Test/bridge.clienttest.runner.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
Also Local fn with directives is replaced incorrectly
Fixes #3558.
> [3558] Unused local function throws NullReferenceException

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/Date.js
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3600/N3621.cs
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
> [3621] DateTime.Date() returns different results if only the seconds field differs in UTC times

- .build/files/Bridge.Min.targets
- .build/specs/Bridge.Min.nuspec
The change is applied in the .nuspec file for Bridge.Min and reflects
in the generated (and extracted) NuGet package.
Also the reference for the file within the corresponding .targets file
needed to be updated.
> [3631] Renames Bridge.Builder.v16.dll to v17

- Bridge/Resources/Date.js
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3700/N3757.cs
Fixes #3757 
- datetime misses kind and ticks causing Equals() to fail later
> change clearTime in order to fix issue 3757

- Bridge/Resources/Array.js
- Bridge/System/Array.cs
- Tests/Batch1/ArrayTests.cs
Implements Array.LongLength and System.Array.Copy for use with longs instead of ints.
> Implement System.Array.LongLength and System.Array.Copy for long indexes

- Bridge/Resources/.generated/bridge.js
- Bridge/Resources/Integer.js
- Tests/Batch3/Batch3.csproj
- Tests/Batch3/BridgeIssues/3900/N3979.cs
- Tests/Runner/Batch1/bridge.js
- Tests/Runner/Batch3/Bridge.Test/bridge.clienttest.batch3.runner.js
- Tests/Runner/Batch3/code.js
> [3979] double.TryParse returns wrong result when input contains + or -

- Compiler/Contract/Config/IAssemblyInfo.cs
- Compiler/Translator/Translator/Translator.InspectAssembly.cs
- Compiler/Translator/Utils/AssemblyInfo.cs
- Tests/Batch1/Bridge/bridge.json
- Tests/Batch3/Bridge/bridge.json
- Tests/Batch4/Bridge/bridge.json
Fixes #3997.
This being accepted will also require a change in Bridge Test project (propagate the setting in Bridge settings created by Bridge.Test.Plugin code), and also in Bridge.Newtonsoft.Json (add the setting so the tests there uses it).
This fix is only relevant for VS2019, which seems to merge references in built assemblies.
> Implements (and uses) the IgnoreDuplicateTypes bridge.js config

- Bridge/System/Array.cs
- Tests/Batch1/ArrayTests.cs
- Tests/Batch1/Collections/Generic/ListTests.cs
- Tests/Batch2/BridgeIssues/N772.cs
Fixes #4033 
- Remove Array.IndexOf and Array.IndexOf instance methods
> Remove Array.LastIndexOf and Array.IndexOf instance methods.

- Compiler/Translator/Emitter/Blocks/GeneratorBlock.cs
- Compiler/TranslatorTests/TestProjects/16/Bridge/reference/Test.BridgeIssues.N4083.js
- Compiler/TranslatorTests/TestProjects/16/Bridge/reference/bridge.report.log
- Compiler/TranslatorTests/TestProjects/16/Bridge/reference/index.html
- Compiler/TranslatorTests/TestProjects/16/BridgeIssues/4000-4999/N4083.cs
- Compiler/TranslatorTests/TestProjects/16/test.csproj
Fixes #4083 
@fabriciomurta 
I cannot build latest Bridge.Test (Method not found exception in Bridge translator) therefore I was not able to add unit test. I will investigate lately what is wrong with Bridge.Test
The following code can be used as unit test
```
using System.Collections.Generic;
using System.Diagnostics;
public class RedBlackNode<V>
{
public string Key;
public V Value;
public RedBlackNode<V> Left;
public RedBlackNode<V> Right;
public static IEnumerable<KeyValuePair<string, V>> GetPairs(RedBlackNode<V> root)
{
if (root == null)
yield break;
Stack<RedBlackNode<V>> stack = new Stack<RedBlackNode<V>>();
RedBlackNode<V> node = root;
LStart:
if (node.Left != null)
{
stack.Push(node);
node = node.Left;
goto LStart;
}
LYieldSelf:
yield return new KeyValuePair<string, V>(node.Key, …
```
> [4083] Crash when iterator uses goto

- Bridge/System/ValueTuple.cs
- Compiler/Translator/Bridge.Translator.csproj
- Compiler/Translator/packages.config
- Compiler/TranslatorTests/Bridge.Translator.Tests.csproj
- Compiler/TranslatorTests/packages.config
When used as Visual Studio's build task, it always uses system references anyway, so this approach would avoid having issues in the future by always using Visual Studio's system libraries.
This would supersede the pull request from ChrML (#4113).
> Switches Microsoft.Build NuGet reference to system reference
